// Curated emoji dataset (~900 emojis) with categories and keyword tags for search.
// Kept in a compact tuple form to minimize bundle size.

export type EmojiCategory =
  | "smileys"
  | "people"
  | "love"
  | "gestures"
  | "animals"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export type EmojiEntry = { c: string; n: string; k?: string };

export const EMOJI_CATEGORIES: { id: EmojiCategory; label: string; icon: string }[] = [
  { id: "smileys", label: "Smileys", icon: "😀" },
  { id: "love", label: "Love", icon: "❤️" },
  { id: "gestures", label: "Gestures", icon: "👋" },
  { id: "people", label: "People", icon: "🧑" },
  { id: "animals", label: "Animals", icon: "🐼" },
  { id: "food", label: "Food", icon: "🍓" },
  { id: "activity", label: "Activity", icon: "⚽" },
  { id: "travel", label: "Travel", icon: "✈️" },
  { id: "objects", label: "Objects", icon: "💡" },
  { id: "symbols", label: "Symbols", icon: "✨" },
  { id: "flags", label: "Flags", icon: "🏳️" },
];

export const EMOJIS: Record<EmojiCategory, EmojiEntry[]> = {
  smileys: [
    { c: "😀", n: "grinning" }, { c: "😃", n: "smiley" }, { c: "😄", n: "smile" },
    { c: "😁", n: "beaming grin" }, { c: "😆", n: "laugh" }, { c: "😅", n: "sweat smile" },
    { c: "🤣", n: "rofl" }, { c: "😂", n: "joy tears" }, { c: "🙂", n: "slight smile" },
    { c: "🙃", n: "upside down" }, { c: "😉", n: "wink" }, { c: "😊", n: "blush happy" },
    { c: "😇", n: "innocent halo" }, { c: "🥰", n: "smiling hearts love" }, { c: "😍", n: "heart eyes" },
    { c: "🤩", n: "star struck" }, { c: "😘", n: "kiss" }, { c: "😗", n: "kissing" },
    { c: "☺️", n: "smiling" }, { c: "😚", n: "kissing closed" }, { c: "😙", n: "kissing smile" },
    { c: "🥲", n: "smile tear" }, { c: "😋", n: "yum tasty" }, { c: "😛", n: "tongue" },
    { c: "😜", n: "wink tongue" }, { c: "🤪", n: "zany" }, { c: "😝", n: "squint tongue" },
    { c: "🤑", n: "money mouth" }, { c: "🤗", n: "hug" }, { c: "🤭", n: "hand over mouth" },
    { c: "🫢", n: "gasp" }, { c: "🫣", n: "peek" }, { c: "🤫", n: "shush" },
    { c: "🤔", n: "thinking" }, { c: "🫡", n: "salute" }, { c: "🤐", n: "zipper" },
    { c: "🤨", n: "raised eyebrow" }, { c: "😐", n: "neutral" }, { c: "😑", n: "expressionless" },
    { c: "😶", n: "no mouth" }, { c: "🫥", n: "dotted" }, { c: "😏", n: "smirk" },
    { c: "😒", n: "unamused" }, { c: "🙄", n: "eye roll" }, { c: "😬", n: "grimace" },
    { c: "🤥", n: "lying" }, { c: "😌", n: "relieved" }, { c: "😔", n: "pensive sad" },
    { c: "😪", n: "sleepy" }, { c: "🤤", n: "drool" }, { c: "😴", n: "sleep" },
    { c: "😷", n: "mask sick" }, { c: "🤒", n: "thermometer" }, { c: "🤕", n: "bandage" },
    { c: "🤢", n: "nauseated" }, { c: "🤮", n: "vomit" }, { c: "🤧", n: "sneeze" },
    { c: "🥵", n: "hot" }, { c: "🥶", n: "cold" }, { c: "🥴", n: "woozy" },
    { c: "😵", n: "dizzy" }, { c: "😵‍💫", n: "spiral" }, { c: "🤯", n: "mind blown" },
    { c: "🤠", n: "cowboy" }, { c: "🥳", n: "party" }, { c: "🥸", n: "disguise" },
    { c: "😎", n: "cool sunglasses" }, { c: "🤓", n: "nerd" }, { c: "🧐", n: "monocle" },
    { c: "😕", n: "confused" }, { c: "🫤", n: "diagonal" }, { c: "😟", n: "worried" },
    { c: "🙁", n: "frown" }, { c: "☹️", n: "sad" }, { c: "😮", n: "open" },
    { c: "😯", n: "hushed" }, { c: "😲", n: "astonished" }, { c: "😳", n: "flushed" },
    { c: "🥺", n: "pleading" }, { c: "🥹", n: "holding tears" }, { c: "😦", n: "frown open" },
    { c: "😧", n: "anguished" }, { c: "😨", n: "fearful" }, { c: "😰", n: "anxious sweat" },
    { c: "😥", n: "sad relieved" }, { c: "😢", n: "cry" }, { c: "😭", n: "sob" },
    { c: "😱", n: "scream" }, { c: "😖", n: "confounded" }, { c: "😣", n: "persevere" },
    { c: "😞", n: "disappointed" }, { c: "😓", n: "downcast" }, { c: "😩", n: "weary" },
    { c: "😫", n: "tired" }, { c: "🥱", n: "yawn" }, { c: "😤", n: "steam nose" },
    { c: "😡", n: "pout angry" }, { c: "😠", n: "angry" }, { c: "🤬", n: "swear" },
    { c: "😈", n: "devil smile" }, { c: "👿", n: "imp angry" }, { c: "💀", n: "skull" },
    { c: "☠️", n: "crossbones" }, { c: "💩", n: "poop" }, { c: "🤡", n: "clown" },
    { c: "👹", n: "ogre" }, { c: "👺", n: "goblin" }, { c: "👻", n: "ghost" },
    { c: "👽", n: "alien" }, { c: "👾", n: "space invader" }, { c: "🤖", n: "robot" },
    { c: "🎃", n: "pumpkin" }, { c: "😺", n: "cat grinning" }, { c: "😸", n: "cat smile" },
    { c: "😹", n: "cat joy" }, { c: "😻", n: "cat heart" }, { c: "😼", n: "cat smirk" },
    { c: "😽", n: "cat kiss" }, { c: "🙀", n: "cat scream" }, { c: "😿", n: "cat cry" },
    { c: "😾", n: "cat pout" },
  ],
  love: [
    { c: "❤️", n: "red heart" }, { c: "🧡", n: "orange heart" }, { c: "💛", n: "yellow heart" },
    { c: "💚", n: "green heart" }, { c: "💙", n: "blue heart" }, { c: "💜", n: "purple heart" },
    { c: "🖤", n: "black heart" }, { c: "🤍", n: "white heart" }, { c: "🤎", n: "brown heart" },
    { c: "💔", n: "broken heart" }, { c: "❤️‍🔥", n: "heart fire" }, { c: "❤️‍🩹", n: "mending heart" },
    { c: "💕", n: "two hearts" }, { c: "💞", n: "revolving hearts" }, { c: "💓", n: "beating heart" },
    { c: "💗", n: "growing heart" }, { c: "💖", n: "sparkling heart" }, { c: "💘", n: "heart arrow" },
    { c: "💝", n: "heart ribbon gift" }, { c: "💟", n: "heart deco" }, { c: "♥️", n: "hearts suit" },
    { c: "💌", n: "love letter" }, { c: "💒", n: "wedding" }, { c: "💍", n: "ring" },
    { c: "👩‍❤️‍👨", n: "couple" }, { c: "👩‍❤️‍👩", n: "couple ww" }, { c: "👨‍❤️‍👨", n: "couple mm" },
    { c: "💏", n: "kiss couple" }, { c: "👩‍❤️‍💋‍👨", n: "kiss" }, { c: "👨‍👩‍👧", n: "family" },
    { c: "🌹", n: "rose" }, { c: "🌷", n: "tulip" }, { c: "💐", n: "bouquet" },
    { c: "🌸", n: "cherry blossom" }, { c: "🌼", n: "flower" }, { c: "💮", n: "white flower" },
    { c: "🥀", n: "wilted" }, { c: "🌺", n: "hibiscus" }, { c: "🌻", n: "sunflower" },
    { c: "💋", n: "kiss mark" }, { c: "👄", n: "lips" }, { c: "💫", n: "dizzy stars" },
    { c: "✨", n: "sparkles" }, { c: "💥", n: "collision" }, { c: "💯", n: "hundred" },
  ],
  gestures: [
    { c: "👋", n: "wave" }, { c: "🤚", n: "raised back" }, { c: "🖐️", n: "hand spread" },
    { c: "✋", n: "raised hand" }, { c: "🖖", n: "vulcan" }, { c: "🫱", n: "right hand" },
    { c: "🫲", n: "left hand" }, { c: "🫳", n: "palm down" }, { c: "🫴", n: "palm up" },
    { c: "👌", n: "ok hand" }, { c: "🤌", n: "pinched fingers" }, { c: "🤏", n: "pinch" },
    { c: "✌️", n: "peace victory" }, { c: "🤞", n: "fingers crossed" }, { c: "🫰", n: "finger heart" },
    { c: "🤟", n: "love you gesture" }, { c: "🤘", n: "rock on horns" }, { c: "🤙", n: "call me" },
    { c: "👈", n: "point left" }, { c: "👉", n: "point right" }, { c: "👆", n: "point up" },
    { c: "🖕", n: "middle finger" }, { c: "👇", n: "point down" }, { c: "☝️", n: "index up" },
    { c: "🫵", n: "point at" }, { c: "👍", n: "thumbs up like" }, { c: "👎", n: "thumbs down dislike" },
    { c: "✊", n: "fist" }, { c: "👊", n: "punch bump" }, { c: "🤛", n: "left fist" },
    { c: "🤜", n: "right fist" }, { c: "👏", n: "clap" }, { c: "🙌", n: "praise raise" },
    { c: "🫶", n: "heart hands" }, { c: "👐", n: "open hands" }, { c: "🤲", n: "palms up" },
    { c: "🤝", n: "handshake" }, { c: "🙏", n: "pray thanks please" }, { c: "✍️", n: "writing" },
    { c: "💅", n: "nails" }, { c: "🤳", n: "selfie" }, { c: "💪", n: "muscle" },
    { c: "🦾", n: "mechanical arm" }, { c: "🦿", n: "mechanical leg" }, { c: "🦵", n: "leg" },
    { c: "🦶", n: "foot" }, { c: "👂", n: "ear" }, { c: "🦻", n: "hearing aid" },
    { c: "👃", n: "nose" }, { c: "🫀", n: "anatomical heart" }, { c: "🫁", n: "lungs" },
    { c: "🧠", n: "brain" }, { c: "🦷", n: "tooth" }, { c: "🦴", n: "bone" },
    { c: "👀", n: "eyes look" }, { c: "👁️", n: "eye" }, { c: "👅", n: "tongue" },
  ],
  people: [
    { c: "👶", n: "baby" }, { c: "🧒", n: "child" }, { c: "👦", n: "boy" }, { c: "👧", n: "girl" },
    { c: "🧑", n: "person" }, { c: "👱", n: "blond" }, { c: "👨", n: "man" }, { c: "🧔", n: "beard" },
    { c: "👩", n: "woman" }, { c: "🧓", n: "older" }, { c: "👴", n: "old man" }, { c: "👵", n: "old woman" },
    { c: "🙍", n: "frowning person" }, { c: "🙎", n: "pouting person" }, { c: "🙅", n: "no gesture" },
    { c: "🙆", n: "ok gesture" }, { c: "💁", n: "tipping hand info" }, { c: "🙋", n: "raising hand" },
    { c: "🧏", n: "deaf" }, { c: "🙇", n: "bowing sorry" }, { c: "🤦", n: "facepalm" },
    { c: "🤷", n: "shrug" }, { c: "👮", n: "police" }, { c: "🕵️", n: "detective" },
    { c: "💂", n: "guard" }, { c: "🥷", n: "ninja" }, { c: "👷", n: "worker" },
    { c: "🫅", n: "royal" }, { c: "🤴", n: "prince" }, { c: "👸", n: "princess" },
    { c: "👳", n: "turban" }, { c: "👲", n: "cap" }, { c: "🧕", n: "headscarf" },
    { c: "🤵", n: "tuxedo" }, { c: "👰", n: "bride veil" }, { c: "🤰", n: "pregnant" },
    { c: "🤱", n: "breastfeeding" }, { c: "👼", n: "angel baby" }, { c: "🎅", n: "santa" },
    { c: "🤶", n: "mrs claus" }, { c: "🦸", n: "superhero" }, { c: "🦹", n: "supervillain" },
    { c: "🧙", n: "mage wizard" }, { c: "🧚", n: "fairy" }, { c: "🧛", n: "vampire" },
    { c: "🧜", n: "merperson" }, { c: "🧝", n: "elf" }, { c: "🧞", n: "genie" },
    { c: "🧟", n: "zombie" }, { c: "💆", n: "massage" }, { c: "💇", n: "haircut" },
    { c: "🚶", n: "walk" }, { c: "🧍", n: "standing" }, { c: "🧎", n: "kneeling" },
    { c: "🏃", n: "run" }, { c: "💃", n: "dance woman" }, { c: "🕺", n: "dance man" },
    { c: "👯", n: "bunny ears" }, { c: "🧖", n: "sauna" }, { c: "🧗", n: "climb" },
    { c: "🤺", n: "fencing" }, { c: "🏇", n: "horse race" }, { c: "⛷️", n: "ski" },
    { c: "🏂", n: "snowboard" }, { c: "🏌️", n: "golf" }, { c: "🏄", n: "surf" },
    { c: "🚣", n: "row boat" }, { c: "🏊", n: "swim" }, { c: "⛹️", n: "basketball play" },
    { c: "🏋️", n: "lift weight" }, { c: "🚴", n: "bike" }, { c: "🚵", n: "mountain bike" },
    { c: "🤸", n: "cartwheel" }, { c: "🤼", n: "wrestle" }, { c: "🤽", n: "water polo" },
    { c: "🤾", n: "handball" }, { c: "🤹", n: "juggle" }, { c: "🧘", n: "yoga meditate" },
    { c: "🛀", n: "bath" }, { c: "🛌", n: "sleep bed" },
  ],
  animals: [
    { c: "🐶", n: "dog" }, { c: "🐱", n: "cat" }, { c: "🐭", n: "mouse" }, { c: "🐹", n: "hamster" },
    { c: "🐰", n: "rabbit bunny" }, { c: "🦊", n: "fox" }, { c: "🐻", n: "bear" }, { c: "🐼", n: "panda" },
    { c: "🐻‍❄️", n: "polar bear" }, { c: "🐨", n: "koala" }, { c: "🐯", n: "tiger" }, { c: "🦁", n: "lion" },
    { c: "🐮", n: "cow" }, { c: "🐷", n: "pig" }, { c: "🐽", n: "pig nose" }, { c: "🐸", n: "frog" },
    { c: "🐵", n: "monkey" }, { c: "🙈", n: "see no evil" }, { c: "🙉", n: "hear no evil" }, { c: "🙊", n: "speak no evil" },
    { c: "🐒", n: "monkey full" }, { c: "🐔", n: "chicken" }, { c: "🐧", n: "penguin" }, { c: "🐦", n: "bird" },
    { c: "🐤", n: "baby chick" }, { c: "🐣", n: "hatching" }, { c: "🐥", n: "chick" }, { c: "🦆", n: "duck" },
    { c: "🦅", n: "eagle" }, { c: "🦉", n: "owl" }, { c: "🦇", n: "bat" }, { c: "🐺", n: "wolf" },
    { c: "🐗", n: "boar" }, { c: "🐴", n: "horse face" }, { c: "🦄", n: "unicorn" }, { c: "🐝", n: "bee" },
    { c: "🪱", n: "worm" }, { c: "🐛", n: "bug" }, { c: "🦋", n: "butterfly" }, { c: "🐌", n: "snail" },
    { c: "🐞", n: "ladybug" }, { c: "🐜", n: "ant" }, { c: "🪰", n: "fly" }, { c: "🪲", n: "beetle" },
    { c: "🦂", n: "scorpion" }, { c: "🕷️", n: "spider" }, { c: "🐢", n: "turtle" }, { c: "🐍", n: "snake" },
    { c: "🦎", n: "lizard" }, { c: "🦖", n: "t-rex" }, { c: "🦕", n: "sauropod dino" }, { c: "🐙", n: "octopus" },
    { c: "🦑", n: "squid" }, { c: "🦐", n: "shrimp" }, { c: "🦞", n: "lobster" }, { c: "🦀", n: "crab" },
    { c: "🐡", n: "blowfish" }, { c: "🐠", n: "tropical fish" }, { c: "🐟", n: "fish" }, { c: "🐬", n: "dolphin" },
    { c: "🐳", n: "whale spout" }, { c: "🐋", n: "whale" }, { c: "🦈", n: "shark" }, { c: "🦭", n: "seal" },
    { c: "🐊", n: "crocodile" }, { c: "🐆", n: "leopard" }, { c: "🦓", n: "zebra" }, { c: "🦍", n: "gorilla" },
    { c: "🦧", n: "orangutan" }, { c: "🐘", n: "elephant" }, { c: "🦣", n: "mammoth" }, { c: "🦛", n: "hippo" },
    { c: "🦏", n: "rhino" }, { c: "🐪", n: "camel" }, { c: "🐫", n: "two hump" }, { c: "🦒", n: "giraffe" },
    { c: "🦘", n: "kangaroo" }, { c: "🦬", n: "bison" }, { c: "🐃", n: "buffalo" }, { c: "🐂", n: "ox" },
    { c: "🐄", n: "cow full" }, { c: "🐎", n: "horse" }, { c: "🐖", n: "pig full" }, { c: "🐏", n: "ram" },
    { c: "🐑", n: "sheep" }, { c: "🦙", n: "llama" }, { c: "🐐", n: "goat" }, { c: "🦌", n: "deer" },
    { c: "🐕", n: "dog full" }, { c: "🐩", n: "poodle" }, { c: "🐈", n: "cat full" }, { c: "🪶", n: "feather" },
    { c: "🐓", n: "rooster" }, { c: "🦃", n: "turkey" }, { c: "🦤", n: "dodo" }, { c: "🦚", n: "peacock" },
    { c: "🦜", n: "parrot" }, { c: "🦢", n: "swan" }, { c: "🦩", n: "flamingo" }, { c: "🕊️", n: "dove peace" },
    { c: "🐇", n: "rabbit full" }, { c: "🦝", n: "raccoon" }, { c: "🦨", n: "skunk" }, { c: "🦡", n: "badger" },
    { c: "🦫", n: "beaver" }, { c: "🦦", n: "otter" }, { c: "🦥", n: "sloth" }, { c: "🐁", n: "mouse full" },
    { c: "🐀", n: "rat" }, { c: "🐿️", n: "squirrel chipmunk" }, { c: "🦔", n: "hedgehog" },
    { c: "🐾", n: "paw prints" }, { c: "🐉", n: "dragon" }, { c: "🐲", n: "dragon face" },
  ],
  food: [
    { c: "🍎", n: "apple red" }, { c: "🍏", n: "apple green" }, { c: "🍐", n: "pear" }, { c: "🍊", n: "orange fruit" },
    { c: "🍋", n: "lemon" }, { c: "🍌", n: "banana" }, { c: "🍉", n: "watermelon" }, { c: "🍇", n: "grapes" },
    { c: "🍓", n: "strawberry" }, { c: "🫐", n: "blueberries" }, { c: "🍈", n: "melon" }, { c: "🍒", n: "cherries" },
    { c: "🍑", n: "peach" }, { c: "🥭", n: "mango" }, { c: "🍍", n: "pineapple" }, { c: "🥥", n: "coconut" },
    { c: "🥝", n: "kiwi" }, { c: "🍅", n: "tomato" }, { c: "🍆", n: "eggplant" }, { c: "🥑", n: "avocado" },
    { c: "🥦", n: "broccoli" }, { c: "🥬", n: "leafy" }, { c: "🥒", n: "cucumber" }, { c: "🌶️", n: "hot pepper" },
    { c: "🫑", n: "bell pepper" }, { c: "🌽", n: "corn" }, { c: "🥕", n: "carrot" }, { c: "🫒", n: "olive" },
    { c: "🧄", n: "garlic" }, { c: "🧅", n: "onion" }, { c: "🥔", n: "potato" }, { c: "🍠", n: "sweet potato" },
    { c: "🥐", n: "croissant" }, { c: "🥯", n: "bagel" }, { c: "🍞", n: "bread" }, { c: "🥖", n: "baguette" },
    { c: "🫓", n: "flatbread" }, { c: "🥨", n: "pretzel" }, { c: "🧀", n: "cheese" }, { c: "🥚", n: "egg" },
    { c: "🍳", n: "cooking egg" }, { c: "🧈", n: "butter" }, { c: "🥞", n: "pancakes" }, { c: "🧇", n: "waffle" },
    { c: "🥓", n: "bacon" }, { c: "🥩", n: "steak meat" }, { c: "🍗", n: "chicken leg" }, { c: "🍖", n: "meat bone" },
    { c: "🦴", n: "bone" }, { c: "🌭", n: "hot dog" }, { c: "🍔", n: "burger" }, { c: "🍟", n: "fries" },
    { c: "🍕", n: "pizza" }, { c: "🥪", n: "sandwich" }, { c: "🌮", n: "taco" }, { c: "🌯", n: "burrito" },
    { c: "🫔", n: "tamale" }, { c: "🥙", n: "pita" }, { c: "🧆", n: "falafel" }, { c: "🥘", n: "paella" },
    { c: "🍲", n: "stew" }, { c: "🫕", n: "fondue" }, { c: "🥣", n: "bowl" }, { c: "🥗", n: "salad" },
    { c: "🍿", n: "popcorn" }, { c: "🧂", n: "salt" }, { c: "🥫", n: "canned" }, { c: "🍱", n: "bento" },
    { c: "🍘", n: "rice cracker" }, { c: "🍙", n: "rice ball" }, { c: "🍚", n: "rice" }, { c: "🍛", n: "curry" },
    { c: "🍜", n: "ramen noodles" }, { c: "🍝", n: "spaghetti pasta" }, { c: "🍢", n: "oden" }, { c: "🍣", n: "sushi" },
    { c: "🍤", n: "shrimp fry" }, { c: "🍥", n: "fish cake" }, { c: "🥮", n: "mooncake" }, { c: "🍡", n: "dango" },
    { c: "🥟", n: "dumpling" }, { c: "🥠", n: "fortune cookie" }, { c: "🥡", n: "takeout" }, { c: "🍦", n: "soft serve" },
    { c: "🍧", n: "shaved ice" }, { c: "🍨", n: "ice cream" }, { c: "🍩", n: "donut" }, { c: "🍪", n: "cookie" },
    { c: "🎂", n: "birthday cake" }, { c: "🍰", n: "cake" }, { c: "🧁", n: "cupcake" }, { c: "🥧", n: "pie" },
    { c: "🍫", n: "chocolate" }, { c: "🍬", n: "candy" }, { c: "🍭", n: "lollipop" }, { c: "🍮", n: "custard" },
    { c: "🍯", n: "honey" }, { c: "🍼", n: "bottle baby" }, { c: "🥛", n: "milk" }, { c: "☕", n: "coffee" },
    { c: "🫖", n: "teapot" }, { c: "🍵", n: "tea" }, { c: "🍶", n: "sake" }, { c: "🍾", n: "champagne" },
    { c: "🍷", n: "wine" }, { c: "🍸", n: "cocktail" }, { c: "🍹", n: "tropical" }, { c: "🍺", n: "beer" },
    { c: "🍻", n: "beers cheers" }, { c: "🥂", n: "clink" }, { c: "🥃", n: "whisky" }, { c: "🥤", n: "cup straw" },
    { c: "🧋", n: "bubble tea" }, { c: "🧃", n: "juice" }, { c: "🧉", n: "mate" }, { c: "🧊", n: "ice" },
    { c: "🥢", n: "chopsticks" }, { c: "🍽️", n: "plate" }, { c: "🍴", n: "fork knife" }, { c: "🥄", n: "spoon" },
  ],
  activity: [
    { c: "⚽", n: "soccer" }, { c: "🏀", n: "basketball" }, { c: "🏈", n: "football" }, { c: "⚾", n: "baseball" },
    { c: "🥎", n: "softball" }, { c: "🎾", n: "tennis" }, { c: "🏐", n: "volleyball" }, { c: "🏉", n: "rugby" },
    { c: "🥏", n: "frisbee" }, { c: "🎱", n: "8ball pool" }, { c: "🪀", n: "yoyo" }, { c: "🏓", n: "ping pong" },
    { c: "🏸", n: "badminton" }, { c: "🏒", n: "hockey" }, { c: "🏑", n: "field hockey" }, { c: "🥍", n: "lacrosse" },
    { c: "🏏", n: "cricket" }, { c: "🪃", n: "boomerang" }, { c: "🥅", n: "goal" }, { c: "⛳", n: "golf hole" },
    { c: "🪁", n: "kite" }, { c: "🏹", n: "archery bow" }, { c: "🎣", n: "fishing" }, { c: "🤿", n: "diving mask" },
    { c: "🥊", n: "boxing glove" }, { c: "🥋", n: "martial arts" }, { c: "🎽", n: "running shirt" }, { c: "🛹", n: "skateboard" },
    { c: "🛼", n: "roller skate" }, { c: "🛷", n: "sled" }, { c: "⛸️", n: "ice skate" }, { c: "🥌", n: "curling" },
    { c: "🎿", n: "skis" }, { c: "🎯", n: "target dart" }, { c: "🪄", n: "wand magic" }, { c: "🎲", n: "dice" },
    { c: "🧩", n: "puzzle" }, { c: "♟️", n: "chess" }, { c: "🎮", n: "gamepad" }, { c: "🕹️", n: "joystick" },
    { c: "🎰", n: "slot" }, { c: "🎳", n: "bowling" }, { c: "🎬", n: "clapper film" }, { c: "🎨", n: "art palette" },
    { c: "🎭", n: "theater" }, { c: "🖼️", n: "picture frame" }, { c: "🎪", n: "circus" }, { c: "🎟️", n: "ticket" },
    { c: "🎫", n: "ticket admission" }, { c: "🎖️", n: "medal military" }, { c: "🏆", n: "trophy" }, { c: "🏅", n: "medal" },
    { c: "🥇", n: "gold medal" }, { c: "🥈", n: "silver medal" }, { c: "🥉", n: "bronze medal" }, { c: "🎗️", n: "ribbon" },
    { c: "🎼", n: "sheet music" }, { c: "🎵", n: "note" }, { c: "🎶", n: "notes" }, { c: "🎙️", n: "mic studio" },
    { c: "🎚️", n: "level slider" }, { c: "🎛️", n: "control knob" }, { c: "🎤", n: "microphone" }, { c: "🎧", n: "headphones" },
    { c: "📻", n: "radio" }, { c: "🎷", n: "sax" }, { c: "🪗", n: "accordion" }, { c: "🎸", n: "guitar" },
    { c: "🎹", n: "piano" }, { c: "🎺", n: "trumpet" }, { c: "🎻", n: "violin" }, { c: "🪕", n: "banjo" },
    { c: "🥁", n: "drum" }, { c: "🪘", n: "long drum" },
  ],
  travel: [
    { c: "🚗", n: "car" }, { c: "🚕", n: "taxi" }, { c: "🚙", n: "suv" }, { c: "🚌", n: "bus" },
    { c: "🚎", n: "trolleybus" }, { c: "🏎️", n: "race car" }, { c: "🚓", n: "police car" }, { c: "🚑", n: "ambulance" },
    { c: "🚒", n: "fire engine" }, { c: "🚐", n: "minibus" }, { c: "🛻", n: "pickup" }, { c: "🚚", n: "truck" },
    { c: "🚛", n: "articulated" }, { c: "🚜", n: "tractor" }, { c: "🛵", n: "scooter" }, { c: "🏍️", n: "motorcycle" },
    { c: "🛺", n: "auto rickshaw" }, { c: "🚲", n: "bicycle" }, { c: "🛴", n: "kick scooter" }, { c: "🚨", n: "police light" },
    { c: "🚔", n: "police car front" }, { c: "🚍", n: "bus front" }, { c: "🚘", n: "car front" }, { c: "🚖", n: "taxi front" },
    { c: "🚡", n: "tram cable" }, { c: "🚠", n: "aerial cable" }, { c: "🚟", n: "suspension" }, { c: "🚃", n: "railway car" },
    { c: "🚋", n: "tram car" }, { c: "🚞", n: "mountain rail" }, { c: "🚝", n: "monorail" }, { c: "🚄", n: "bullet train" },
    { c: "🚅", n: "high speed" }, { c: "🚈", n: "light rail" }, { c: "🚂", n: "steam" }, { c: "🚆", n: "train" },
    { c: "🚇", n: "metro" }, { c: "🚊", n: "tram" }, { c: "🚉", n: "station" }, { c: "✈️", n: "plane" },
    { c: "🛩️", n: "small plane" }, { c: "🛫", n: "takeoff" }, { c: "🛬", n: "landing" }, { c: "🪂", n: "parachute" },
    { c: "💺", n: "seat" }, { c: "🚀", n: "rocket" }, { c: "🛸", n: "ufo" }, { c: "🚁", n: "helicopter" },
    { c: "🛶", n: "canoe" }, { c: "⛵", n: "sailboat" }, { c: "🚤", n: "speedboat" }, { c: "🛥️", n: "motor boat" },
    { c: "🛳️", n: "cruise" }, { c: "⛴️", n: "ferry" }, { c: "🚢", n: "ship" }, { c: "⚓", n: "anchor" },
    { c: "🪝", n: "hook" }, { c: "⛽", n: "fuel" }, { c: "🚧", n: "construction" }, { c: "🚦", n: "traffic light" },
    { c: "🚥", n: "horizontal light" }, { c: "🗺️", n: "map" }, { c: "🗿", n: "moai" }, { c: "🗽", n: "liberty" },
    { c: "🗼", n: "tokyo tower" }, { c: "🏰", n: "castle" }, { c: "🏯", n: "japan castle" }, { c: "🏟️", n: "stadium" },
    { c: "🎡", n: "ferris" }, { c: "🎢", n: "roller coaster" }, { c: "🎠", n: "carousel" }, { c: "⛲", n: "fountain" },
    { c: "⛱️", n: "umbrella beach" }, { c: "🏖️", n: "beach" }, { c: "🏝️", n: "desert island" }, { c: "🏜️", n: "desert" },
    { c: "🌋", n: "volcano" }, { c: "⛰️", n: "mountain" }, { c: "🏔️", n: "snow mountain" }, { c: "🗻", n: "fuji" },
    { c: "🏕️", n: "camping" }, { c: "⛺", n: "tent" }, { c: "🏞️", n: "national park" }, { c: "🛣️", n: "motorway" },
    { c: "🛤️", n: "railway" }, { c: "🌅", n: "sunrise" }, { c: "🌄", n: "sunrise mountain" }, { c: "🌠", n: "shooting star" },
    { c: "🎇", n: "sparkler" }, { c: "🎆", n: "fireworks" }, { c: "🌇", n: "sunset city" }, { c: "🌆", n: "cityscape dusk" },
    { c: "🏙️", n: "cityscape" }, { c: "🌃", n: "night stars" }, { c: "🌌", n: "milky way" }, { c: "🌉", n: "bridge night" },
    { c: "🌁", n: "foggy" }, { c: "🏘️", n: "houses" }, { c: "🏚️", n: "derelict" }, { c: "🏡", n: "house garden" },
    { c: "🏠", n: "house" }, { c: "🏢", n: "office" }, { c: "🏬", n: "department" }, { c: "🏣", n: "japan post" },
    { c: "🏤", n: "european post" }, { c: "🏥", n: "hospital" }, { c: "🏦", n: "bank" }, { c: "🏨", n: "hotel" },
    { c: "🏪", n: "convenience" }, { c: "🏫", n: "school" }, { c: "🏩", n: "love hotel" }, { c: "💒", n: "wedding chapel" },
    { c: "⛪", n: "church" }, { c: "🕌", n: "mosque" }, { c: "🛕", n: "hindu temple" }, { c: "🕍", n: "synagogue" },
    { c: "⛩️", n: "shinto" },
  ],
  objects: [
    { c: "⌚", n: "watch" }, { c: "📱", n: "phone" }, { c: "📲", n: "phone arrow" }, { c: "💻", n: "laptop" },
    { c: "⌨️", n: "keyboard" }, { c: "🖥️", n: "desktop" }, { c: "🖨️", n: "printer" }, { c: "🖱️", n: "mouse computer" },
    { c: "🖲️", n: "trackball" }, { c: "🕹️", n: "joystick" }, { c: "🗜️", n: "clamp" }, { c: "💽", n: "minidisc" },
    { c: "💾", n: "floppy save" }, { c: "💿", n: "cd" }, { c: "📀", n: "dvd" }, { c: "📼", n: "vhs" },
    { c: "📷", n: "camera" }, { c: "📸", n: "camera flash" }, { c: "📹", n: "video cam" }, { c: "🎥", n: "movie cam" },
    { c: "📽️", n: "projector" }, { c: "🎞️", n: "film frames" }, { c: "📞", n: "telephone" }, { c: "☎️", n: "phone old" },
    { c: "📟", n: "pager" }, { c: "📠", n: "fax" }, { c: "📺", n: "tv" }, { c: "📻", n: "radio object" },
    { c: "🧭", n: "compass" }, { c: "⏱️", n: "stopwatch" }, { c: "⏲️", n: "timer" }, { c: "⏰", n: "alarm" },
    { c: "🕰️", n: "mantelpiece" }, { c: "⌛", n: "hourglass done" }, { c: "⏳", n: "hourglass flow" }, { c: "📡", n: "satellite" },
    { c: "🔋", n: "battery" }, { c: "🔌", n: "plug" }, { c: "💡", n: "bulb idea" }, { c: "🔦", n: "flashlight" },
    { c: "🕯️", n: "candle" }, { c: "🪔", n: "diya" }, { c: "🧯", n: "extinguisher" }, { c: "🛢️", n: "oil drum" },
    { c: "💸", n: "money flying" }, { c: "💵", n: "dollar" }, { c: "💴", n: "yen" }, { c: "💶", n: "euro" },
    { c: "💷", n: "pound" }, { c: "🪙", n: "coin" }, { c: "💰", n: "bag money" }, { c: "💳", n: "card credit" },
    { c: "🧾", n: "receipt" }, { c: "💎", n: "gem" }, { c: "⚖️", n: "balance scale" }, { c: "🪜", n: "ladder" },
    { c: "🧰", n: "toolbox" }, { c: "🪛", n: "screwdriver" }, { c: "🔧", n: "wrench" }, { c: "🔨", n: "hammer" },
    { c: "⚒️", n: "hammer pick" }, { c: "🛠️", n: "tools" }, { c: "⛏️", n: "pick" }, { c: "🪚", n: "saw" },
    { c: "🔩", n: "nut bolt" }, { c: "⚙️", n: "gear" }, { c: "🪤", n: "trap" }, { c: "🧱", n: "brick" },
    { c: "⛓️", n: "chains" }, { c: "🧲", n: "magnet" }, { c: "🔫", n: "water gun" }, { c: "💣", n: "bomb" },
    { c: "🧨", n: "firecracker" }, { c: "🪓", n: "axe" }, { c: "🔪", n: "kitchen knife" }, { c: "🗡️", n: "dagger" },
    { c: "⚔️", n: "swords" }, { c: "🛡️", n: "shield" }, { c: "🚬", n: "smoking" }, { c: "⚰️", n: "coffin" },
    { c: "🪦", n: "headstone" }, { c: "⚱️", n: "urn" }, { c: "🏺", n: "amphora" }, { c: "🔮", n: "crystal ball" },
    { c: "📿", n: "prayer beads" }, { c: "🧿", n: "nazar" }, { c: "💈", n: "barber" }, { c: "🔭", n: "telescope" },
    { c: "🔬", n: "microscope" }, { c: "🕳️", n: "hole" }, { c: "🩹", n: "adhesive bandage" }, { c: "🩺", n: "stethoscope" },
    { c: "💊", n: "pill" }, { c: "💉", n: "syringe" }, { c: "🩸", n: "blood" }, { c: "🧬", n: "dna" },
    { c: "🦠", n: "microbe" }, { c: "🧫", n: "petri" }, { c: "🧪", n: "test tube" }, { c: "🌡️", n: "thermometer" },
    { c: "🧹", n: "broom" }, { c: "🪠", n: "plunger" }, { c: "🧺", n: "basket" }, { c: "🧻", n: "toilet paper" },
    { c: "🚽", n: "toilet" }, { c: "🚰", n: "potable water" }, { c: "🚿", n: "shower" }, { c: "🛁", n: "bathtub" },
    { c: "🛀", n: "bath" }, { c: "🧼", n: "soap" }, { c: "🪥", n: "toothbrush" }, { c: "🪒", n: "razor" },
    { c: "🧽", n: "sponge" }, { c: "🪣", n: "bucket" }, { c: "🧴", n: "lotion" }, { c: "🛎️", n: "bellhop bell" },
    { c: "🔑", n: "key" }, { c: "🗝️", n: "old key" }, { c: "🚪", n: "door" }, { c: "🪑", n: "chair" },
    { c: "🛋️", n: "couch" }, { c: "🛏️", n: "bed" }, { c: "🪞", n: "mirror" }, { c: "🪟", n: "window" },
    { c: "🖼️", n: "picture" }, { c: "🛒", n: "cart" }, { c: "🎁", n: "gift present" }, { c: "🎈", n: "balloon" },
    { c: "🎏", n: "carp flag" }, { c: "🎀", n: "ribbon" }, { c: "🎊", n: "confetti" }, { c: "🎉", n: "party popper" },
    { c: "🎎", n: "japanese dolls" }, { c: "🎐", n: "wind chime" }, { c: "🎌", n: "crossed flags" }, { c: "🏮", n: "lantern" },
    { c: "🧧", n: "red envelope" }, { c: "📧", n: "email" }, { c: "📨", n: "envelope arrow" }, { c: "📩", n: "envelope down" },
    { c: "📤", n: "outbox" }, { c: "📥", n: "inbox" }, { c: "📦", n: "package" }, { c: "📫", n: "mailbox" },
    { c: "📪", n: "closed mailbox" }, { c: "📬", n: "mail with mail" }, { c: "📭", n: "no mail" }, { c: "📮", n: "postbox" },
    { c: "📯", n: "horn" }, { c: "📜", n: "scroll" }, { c: "📃", n: "page curl" }, { c: "📄", n: "page facing" },
    { c: "📑", n: "bookmark tabs" }, { c: "🧾", n: "receipt object" }, { c: "📊", n: "bar chart" }, { c: "📈", n: "chart up" },
    { c: "📉", n: "chart down" }, { c: "🗒️", n: "spiral note" }, { c: "🗓️", n: "spiral calendar" }, { c: "📆", n: "tear off" },
    { c: "📅", n: "calendar" }, { c: "🗑️", n: "wastebasket" }, { c: "📇", n: "card index" }, { c: "🗃️", n: "card file" },
    { c: "🗳️", n: "ballot" }, { c: "🗄️", n: "cabinet" }, { c: "📋", n: "clipboard" }, { c: "📁", n: "folder" },
    { c: "📂", n: "open folder" }, { c: "🗂️", n: "dividers" }, { c: "🗞️", n: "rolled paper" }, { c: "📰", n: "newspaper" },
    { c: "📓", n: "notebook" }, { c: "📔", n: "notebook decor" }, { c: "📒", n: "ledger" }, { c: "📕", n: "closed book" },
    { c: "📗", n: "green book" }, { c: "📘", n: "blue book" }, { c: "📙", n: "orange book" }, { c: "📚", n: "books" },
    { c: "📖", n: "open book" }, { c: "🔖", n: "bookmark" }, { c: "🧷", n: "safety pin" }, { c: "🔗", n: "link" },
    { c: "📎", n: "paperclip" }, { c: "🖇️", n: "linked paperclips" }, { c: "📐", n: "triangular ruler" }, { c: "📏", n: "ruler" },
    { c: "🧮", n: "abacus" }, { c: "📌", n: "pushpin" }, { c: "📍", n: "round pushpin location" }, { c: "✂️", n: "scissors" },
    { c: "🖊️", n: "pen" }, { c: "🖋️", n: "fountain pen" }, { c: "✒️", n: "black nib" }, { c: "🖌️", n: "paintbrush" },
    { c: "🖍️", n: "crayon" }, { c: "📝", n: "memo write" }, { c: "✏️", n: "pencil" }, { c: "🔍", n: "magnify left" },
    { c: "🔎", n: "magnify right" }, { c: "🔏", n: "lock pen" }, { c: "🔐", n: "lock key" }, { c: "🔒", n: "lock" },
    { c: "🔓", n: "unlock" }, { c: "👕", n: "shirt" }, { c: "👔", n: "necktie" }, { c: "👖", n: "jeans" },
    { c: "🧣", n: "scarf" }, { c: "🧤", n: "gloves" }, { c: "🧥", n: "coat" }, { c: "🧦", n: "socks" },
    { c: "👗", n: "dress" }, { c: "👘", n: "kimono" }, { c: "🥻", n: "sari" }, { c: "🩱", n: "one piece swim" },
    { c: "🩲", n: "briefs" }, { c: "🩳", n: "shorts" }, { c: "👙", n: "bikini" }, { c: "👚", n: "blouse" },
    { c: "👛", n: "purse" }, { c: "👜", n: "handbag" }, { c: "👝", n: "clutch" }, { c: "🛍️", n: "shopping bags" },
    { c: "🎒", n: "backpack" }, { c: "🩴", n: "flip flops" }, { c: "👞", n: "man shoe" }, { c: "👟", n: "sneaker" },
    { c: "🥾", n: "hiking boot" }, { c: "🥿", n: "flat shoe" }, { c: "👠", n: "heel" }, { c: "👡", n: "sandal" },
    { c: "🩰", n: "ballet" }, { c: "👢", n: "boot" }, { c: "👑", n: "crown" }, { c: "👒", n: "sun hat" },
    { c: "🎩", n: "top hat" }, { c: "🎓", n: "grad cap" }, { c: "🧢", n: "cap" }, { c: "🪖", n: "helmet" },
    { c: "⛑️", n: "rescue helmet" }, { c: "📿", n: "beads" }, { c: "💄", n: "lipstick" }, { c: "💍", n: "ring" },
    { c: "💎", n: "gem stone" }, { c: "🌂", n: "umbrella" }, { c: "☂️", n: "umbrella open" }, { c: "🧳", n: "luggage" },
  ],
  symbols: [
    { c: "❤️", n: "heart" }, { c: "💯", n: "100" }, { c: "💢", n: "anger" }, { c: "💬", n: "speech" },
    { c: "👁️‍🗨️", n: "eye speech" }, { c: "🗨️", n: "speech left" }, { c: "🗯️", n: "right anger" }, { c: "💭", n: "thought" },
    { c: "💤", n: "zzz" }, { c: "🕉️", n: "om" }, { c: "☸️", n: "dharma" }, { c: "✡️", n: "star david" },
    { c: "☯️", n: "yin yang" }, { c: "☦️", n: "orthodox cross" }, { c: "🛐", n: "worship" }, { c: "⛎", n: "ophiuchus" },
    { c: "♈", n: "aries" }, { c: "♉", n: "taurus" }, { c: "♊", n: "gemini" }, { c: "♋", n: "cancer" },
    { c: "♌", n: "leo" }, { c: "♍", n: "virgo" }, { c: "♎", n: "libra" }, { c: "♏", n: "scorpio" },
    { c: "♐", n: "sagittarius" }, { c: "♑", n: "capricorn" }, { c: "♒", n: "aquarius" }, { c: "♓", n: "pisces" },
    { c: "🆔", n: "id" }, { c: "⚛️", n: "atom" }, { c: "🉑", n: "accept" }, { c: "☢️", n: "radioactive" },
    { c: "☣️", n: "biohazard" }, { c: "📴", n: "phone off" }, { c: "📳", n: "vibrate" }, { c: "🈶", n: "not free" },
    { c: "🈚", n: "free" }, { c: "🈸", n: "application" }, { c: "🈺", n: "open business" }, { c: "🈷️", n: "monthly" },
    { c: "✴️", n: "eight point star" }, { c: "🆚", n: "vs" }, { c: "💮", n: "white flower symbol" }, { c: "🉐", n: "bargain" },
    { c: "㊙️", n: "secret" }, { c: "㊗️", n: "congrats" }, { c: "🈴", n: "passing" }, { c: "🈵", n: "no vacancy" },
    { c: "🈹", n: "discount" }, { c: "🈲", n: "prohibited" }, { c: "🅰️", n: "a" }, { c: "🅱️", n: "b" },
    { c: "🆎", n: "ab" }, { c: "🆑", n: "cl" }, { c: "🅾️", n: "o" }, { c: "🆘", n: "sos" },
    { c: "❌", n: "cross mark" }, { c: "⭕", n: "circle" }, { c: "🛑", n: "stop" }, { c: "⛔", n: "no entry" },
    { c: "📛", n: "name badge" }, { c: "🚫", n: "prohibit" }, { c: "💯", n: "hundred symbol" }, { c: "💢", n: "anger sym" },
    { c: "♨️", n: "hot springs" }, { c: "🚷", n: "no pedestrian" }, { c: "🚯", n: "no litter" }, { c: "🚳", n: "no bike" },
    { c: "🚱", n: "not potable" }, { c: "🔞", n: "18" }, { c: "📵", n: "no phone" }, { c: "🚭", n: "no smoke" },
    { c: "❗", n: "exclamation" }, { c: "❕", n: "white exclamation" }, { c: "❓", n: "question" }, { c: "❔", n: "white question" },
    { c: "‼️", n: "double bang" }, { c: "⁉️", n: "interrobang" }, { c: "🔅", n: "dim" }, { c: "🔆", n: "bright" },
    { c: "〽️", n: "part alt" }, { c: "⚠️", n: "warning" }, { c: "🚸", n: "children crossing" }, { c: "🔱", n: "trident" },
    { c: "⚜️", n: "fleur" }, { c: "🔰", n: "beginner" }, { c: "♻️", n: "recycle" }, { c: "✅", n: "check green" },
    { c: "🈯", n: "reserved" }, { c: "💹", n: "chart yen" }, { c: "❇️", n: "sparkle" }, { c: "✳️", n: "eight star" },
    { c: "❎", n: "cross button" }, { c: "🌐", n: "globe meridians" }, { c: "💠", n: "diamond dot" }, { c: "Ⓜ️", n: "circled m" },
    { c: "🌀", n: "cyclone" }, { c: "💤", n: "sleep zzz" }, { c: "🏧", n: "atm" }, { c: "🚾", n: "wc" },
    { c: "♿", n: "wheelchair" }, { c: "🅿️", n: "parking" }, { c: "🛗", n: "elevator" }, { c: "🈳", n: "vacancy" },
    { c: "🈂️", n: "sa" }, { c: "🛂", n: "passport" }, { c: "🛃", n: "customs" }, { c: "🛄", n: "baggage claim" },
    { c: "🛅", n: "left luggage" }, { c: "🚹", n: "men" }, { c: "🚺", n: "women" }, { c: "🚼", n: "baby" },
    { c: "🚻", n: "restroom" }, { c: "🚮", n: "litter" }, { c: "🎦", n: "cinema" }, { c: "📶", n: "signal" },
    { c: "🈁", n: "here" }, { c: "🔣", n: "input symbols" }, { c: "ℹ️", n: "info" }, { c: "🔤", n: "abc" },
    { c: "🔡", n: "abcd lower" }, { c: "🔠", n: "abcd upper" }, { c: "🆖", n: "ng" }, { c: "🆗", n: "ok" },
    { c: "🆙", n: "up" }, { c: "🆒", n: "cool" }, { c: "🆓", n: "free" }, { c: "0️⃣", n: "0" },
    { c: "1️⃣", n: "1" }, { c: "2️⃣", n: "2" }, { c: "3️⃣", n: "3" }, { c: "4️⃣", n: "4" },
    { c: "5️⃣", n: "5" }, { c: "6️⃣", n: "6" }, { c: "7️⃣", n: "7" }, { c: "8️⃣", n: "8" },
    { c: "9️⃣", n: "9" }, { c: "🔟", n: "10" }, { c: "🔢", n: "1234" }, { c: "#️⃣", n: "hash" },
    { c: "*️⃣", n: "asterisk" }, { c: "⏏️", n: "eject" }, { c: "▶️", n: "play" }, { c: "⏸️", n: "pause" },
    { c: "⏯️", n: "play pause" }, { c: "⏹️", n: "stop button" }, { c: "⏺️", n: "record" }, { c: "⏭️", n: "next" },
    { c: "⏮️", n: "previous" }, { c: "⏩", n: "fast forward" }, { c: "⏪", n: "rewind" }, { c: "⏫", n: "fast up" },
    { c: "⏬", n: "fast down" }, { c: "◀️", n: "reverse" }, { c: "🔼", n: "up small" }, { c: "🔽", n: "down small" },
    { c: "➡️", n: "right arrow" }, { c: "⬅️", n: "left arrow" }, { c: "⬆️", n: "up arrow" }, { c: "⬇️", n: "down arrow" },
    { c: "↗️", n: "up right" }, { c: "↘️", n: "down right" }, { c: "↙️", n: "down left" }, { c: "↖️", n: "up left" },
    { c: "↕️", n: "vertical" }, { c: "↔️", n: "horizontal" }, { c: "↪️", n: "left hook" }, { c: "↩️", n: "right hook" },
    { c: "⤴️", n: "up curve" }, { c: "⤵️", n: "down curve" }, { c: "🔀", n: "shuffle" }, { c: "🔁", n: "repeat" },
    { c: "🔂", n: "repeat one" }, { c: "🔄", n: "arrows circular" }, { c: "🔃", n: "clockwise" }, { c: "🎵", n: "musical note" },
    { c: "🎶", n: "musical notes" }, { c: "➕", n: "plus" }, { c: "➖", n: "minus" }, { c: "➗", n: "divide" },
    { c: "✖️", n: "multiply" }, { c: "🟰", n: "equals" }, { c: "♾️", n: "infinity" }, { c: "💲", n: "dollar sign" },
    { c: "💱", n: "currency exchange" }, { c: "™️", n: "trademark" }, { c: "©️", n: "copyright" }, { c: "®️", n: "registered" },
    { c: "〰️", n: "wavy dash" }, { c: "➰", n: "curly loop" }, { c: "➿", n: "double loop" }, { c: "🔚", n: "end" },
    { c: "🔙", n: "back" }, { c: "🔛", n: "on" }, { c: "🔝", n: "top" }, { c: "🔜", n: "soon" },
    { c: "✔️", n: "check mark" }, { c: "☑️", n: "checkbox" }, { c: "🔘", n: "radio button" }, { c: "🔴", n: "red circle" },
    { c: "🟠", n: "orange circle" }, { c: "🟡", n: "yellow circle" }, { c: "🟢", n: "green circle" }, { c: "🔵", n: "blue circle" },
    { c: "🟣", n: "purple circle" }, { c: "⚫", n: "black circle" }, { c: "⚪", n: "white circle" }, { c: "🟤", n: "brown circle" },
    { c: "🔺", n: "red triangle up" }, { c: "🔻", n: "red triangle down" }, { c: "🔸", n: "diamond small orange" }, { c: "🔹", n: "diamond small blue" },
    { c: "🔶", n: "diamond large orange" }, { c: "🔷", n: "diamond large blue" }, { c: "🔳", n: "black button" }, { c: "🔲", n: "white button" },
    { c: "▪️", n: "black small square" }, { c: "▫️", n: "white small square" }, { c: "◾", n: "black medium" }, { c: "◽", n: "white medium" },
    { c: "◼️", n: "black large" }, { c: "◻️", n: "white large" }, { c: "🟥", n: "red square" }, { c: "🟧", n: "orange square" },
    { c: "🟨", n: "yellow square" }, { c: "🟩", n: "green square" }, { c: "🟦", n: "blue square" }, { c: "🟪", n: "purple square" },
    { c: "⬛", n: "black big square" }, { c: "⬜", n: "white big square" }, { c: "🟫", n: "brown square" }, { c: "🔈", n: "speaker low" },
    { c: "🔇", n: "mute" }, { c: "🔉", n: "speaker med" }, { c: "🔊", n: "speaker loud" }, { c: "🔔", n: "bell" },
    { c: "🔕", n: "bell mute" }, { c: "📣", n: "megaphone" }, { c: "📢", n: "loudspeaker" }, { c: "👁️‍🗨️", n: "eye speech bubble" },
    { c: "💬", n: "speech balloon" }, { c: "💭", n: "thought balloon" }, { c: "🗯️", n: "anger balloon" }, { c: "♠️", n: "spade" },
    { c: "♣️", n: "club" }, { c: "♥️", n: "heart suit" }, { c: "♦️", n: "diamond" }, { c: "🃏", n: "joker" },
    { c: "🀄", n: "mahjong" }, { c: "🎴", n: "flower cards" }, { c: "☘️", n: "shamrock" }, { c: "🍀", n: "four leaf" },
    { c: "🌟", n: "glowing star" }, { c: "⭐", n: "star" }, { c: "🌠", n: "shooting" }, { c: "☄️", n: "comet" },
    { c: "💫", n: "dizzy star" }, { c: "🔥", n: "fire" }, { c: "🌈", n: "rainbow" }, { c: "☀️", n: "sun" },
    { c: "🌤️", n: "sun cloud" }, { c: "⛅", n: "sun behind cloud" }, { c: "🌥️", n: "cloud sun" }, { c: "🌦️", n: "sun rain" },
    { c: "☁️", n: "cloud" }, { c: "🌧️", n: "rain cloud" }, { c: "⛈️", n: "storm" }, { c: "🌩️", n: "lightning cloud" },
    { c: "🌨️", n: "snow cloud" }, { c: "❄️", n: "snowflake" }, { c: "☃️", n: "snowman" }, { c: "⛄", n: "snow no snow" },
    { c: "🌬️", n: "wind" }, { c: "💨", n: "dash wind" }, { c: "💧", n: "droplet" }, { c: "💦", n: "sweat drops" },
    { c: "🌊", n: "wave water" }, { c: "🌫️", n: "fog" }, { c: "🌪️", n: "tornado" }, { c: "⚡", n: "lightning" },
    { c: "🌞", n: "sun face" }, { c: "🌛", n: "first quarter face" }, { c: "🌜", n: "last quarter face" }, { c: "🌚", n: "new moon face" },
    { c: "🌝", n: "full moon face" }, { c: "🌙", n: "crescent" }, { c: "🌘", n: "waning crescent" }, { c: "🌗", n: "last quarter" },
    { c: "🌖", n: "waning gibbous" }, { c: "🌕", n: "full moon" }, { c: "🌔", n: "waxing gibbous" }, { c: "🌓", n: "first quarter" },
    { c: "🌒", n: "waxing crescent" }, { c: "🌑", n: "new moon" }, { c: "🌎", n: "americas" }, { c: "🌍", n: "africa europe" },
    { c: "🌏", n: "asia oceania" }, { c: "🪐", n: "saturn" },
  ],
  flags: [
    { c: "🏳️", n: "white flag" }, { c: "🏴", n: "black flag" }, { c: "🏁", n: "chequered" }, { c: "🚩", n: "triangular" },
    { c: "🏳️‍🌈", n: "rainbow pride" }, { c: "🏳️‍⚧️", n: "trans" }, { c: "🏴‍☠️", n: "pirate" }, { c: "🇺🇸", n: "usa united states" },
    { c: "🇬🇧", n: "uk britain" }, { c: "🇨🇦", n: "canada" }, { c: "🇦🇺", n: "australia" }, { c: "🇩🇪", n: "germany" },
    { c: "🇫🇷", n: "france" }, { c: "🇪🇸", n: "spain" }, { c: "🇮🇹", n: "italy" }, { c: "🇯🇵", n: "japan" },
    { c: "🇰🇷", n: "korea south" }, { c: "🇨🇳", n: "china" }, { c: "🇮🇳", n: "india" }, { c: "🇧🇷", n: "brazil" },
    { c: "🇲🇽", n: "mexico" }, { c: "🇷🇺", n: "russia" }, { c: "🇳🇱", n: "netherlands" }, { c: "🇸🇪", n: "sweden" },
    { c: "🇳🇴", n: "norway" }, { c: "🇩🇰", n: "denmark" }, { c: "🇫🇮", n: "finland" }, { c: "🇵🇱", n: "poland" },
    { c: "🇵🇹", n: "portugal" }, { c: "🇬🇷", n: "greece" }, { c: "🇹🇷", n: "turkey" }, { c: "🇮🇪", n: "ireland" },
    { c: "🇨🇭", n: "switzerland" }, { c: "🇦🇹", n: "austria" }, { c: "🇧🇪", n: "belgium" }, { c: "🇨🇿", n: "czechia" },
    { c: "🇭🇺", n: "hungary" }, { c: "🇷🇴", n: "romania" }, { c: "🇺🇦", n: "ukraine" }, { c: "🇮🇱", n: "israel" },
    { c: "🇸🇦", n: "saudi arabia" }, { c: "🇦🇪", n: "uae" }, { c: "🇪🇬", n: "egypt" }, { c: "🇿🇦", n: "south africa" },
    { c: "🇳🇬", n: "nigeria" }, { c: "🇰🇪", n: "kenya" }, { c: "🇦🇷", n: "argentina" }, { c: "🇨🇱", n: "chile" },
    { c: "🇨🇴", n: "colombia" }, { c: "🇵🇪", n: "peru" }, { c: "🇻🇪", n: "venezuela" }, { c: "🇳🇿", n: "new zealand" },
    { c: "🇮🇩", n: "indonesia" }, { c: "🇹🇭", n: "thailand" }, { c: "🇻🇳", n: "vietnam" }, { c: "🇵🇭", n: "philippines" },
    { c: "🇲🇾", n: "malaysia" }, { c: "🇸🇬", n: "singapore" }, { c: "🇵🇰", n: "pakistan" }, { c: "🇧🇩", n: "bangladesh" },
    { c: "🇱🇰", n: "sri lanka" }, { c: "🇮🇷", n: "iran" }, { c: "🇮🇶", n: "iraq" }, { c: "🇦🇫", n: "afghanistan" },
    { c: "🇲🇦", n: "morocco" }, { c: "🇩🇿", n: "algeria" }, { c: "🇹🇳", n: "tunisia" }, { c: "🇪🇹", n: "ethiopia" },
    { c: "🇬🇭", n: "ghana" }, { c: "🇨🇺", n: "cuba" }, { c: "🇩🇴", n: "dominican" }, { c: "🇯🇲", n: "jamaica" },
    { c: "🇭🇰", n: "hong kong" }, { c: "🇹🇼", n: "taiwan" }, { c: "🇰🇵", n: "north korea" }, { c: "🇮🇸", n: "iceland" },
  ],
};

export function searchEmojis(query: string, limit = 200): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: EmojiEntry[] = [];
  for (const cat of Object.values(EMOJIS)) {
    for (const e of cat) {
      if (e.n.includes(q) || (e.k && e.k.includes(q))) {
        out.push(e);
        if (out.length >= limit) return out;
      }
    }
  }
  return out;
}

const RECENT_KEY = "emoji.recent.v1";
export function loadRecentEmojis(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(RECENT_KEY);
    return raw ? (JSON.parse(raw) as string[]) : [];
  } catch {
    return [];
  }
}
export function pushRecentEmoji(char: string) {
  if (typeof window === "undefined") return;
  try {
    const list = loadRecentEmojis().filter((c) => c !== char);
    list.unshift(char);
    window.localStorage.setItem(RECENT_KEY, JSON.stringify(list.slice(0, 32)));
  } catch {
    /* noop */
  }
}
