/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWishlistRouteImport } from './routes/_authenticated/app.wishlist'
import { Route as AuthenticatedAppWatchRouteImport } from './routes/_authenticated/app.watch'
import { Route as AuthenticatedAppScribbleRouteImport } from './routes/_authenticated/app.scribble'
import { Route as AuthenticatedAppPuzzleRouteImport } from './routes/_authenticated/app.puzzle'
import { Route as AuthenticatedAppPlayRouteImport } from './routes/_authenticated/app.play'
import { Route as AuthenticatedAppPartnerRouteImport } from './routes/_authenticated/app.partner'
import { Route as AuthenticatedAppPaintRouteImport } from './routes/_authenticated/app.paint'
import { Route as AuthenticatedAppMoviesRouteImport } from './routes/_authenticated/app.movies'
import { Route as AuthenticatedAppMoodRouteImport } from './routes/_authenticated/app.mood'
import { Route as AuthenticatedAppMemoryChallengeRouteImport } from './routes/_authenticated/app.memory-challenge'
import { Route as AuthenticatedAppMemoriesRouteImport } from './routes/_authenticated/app.memories'
import { Route as AuthenticatedAppMeRouteImport } from './routes/_authenticated/app.me'
import { Route as AuthenticatedAppLoveQuizRouteImport } from './routes/_authenticated/app.love-quiz'
import { Route as AuthenticatedAppInviteRouteImport } from './routes/_authenticated/app.invite'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppFriendsRouteImport } from './routes/_authenticated/app.friends'
import { Route as AuthenticatedAppDailyChallengeRouteImport } from './routes/_authenticated/app.daily-challenge'
import { Route as AuthenticatedAppAnniversaryRouteImport } from './routes/_authenticated/app.anniversary'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppMoviesIndexRouteImport } from './routes/_authenticated/app.movies.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAppMoviesIdRouteImport } from './routes/_authenticated/app.movies.$id'
import { Route as AuthenticatedAppGamesGameRouteImport } from './routes/_authenticated/app.games.$game'
import { Route as AuthenticatedAppChatPeerIdRouteImport } from './routes/_authenticated/app.chat.$peerId'
import { Route as AuthenticatedAppCallPeerIdRouteImport } from './routes/_authenticated/app.call.$peerId'
import { Route as AuthenticatedAppMoviesIdWatchRouteImport } from './routes/_authenticated/app.movies.$id.watch'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWishlistRoute =
  AuthenticatedAppWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWatchRoute = AuthenticatedAppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScribbleRoute =
  AuthenticatedAppScribbleRouteImport.update({
    id: '/scribble',
    path: '/scribble',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPuzzleRoute = AuthenticatedAppPuzzleRouteImport.update({
  id: '/puzzle',
  path: '/puzzle',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlayRoute = AuthenticatedAppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPartnerRoute = AuthenticatedAppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaintRoute = AuthenticatedAppPaintRouteImport.update({
  id: '/paint',
  path: '/paint',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMoviesRoute = AuthenticatedAppMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMoodRoute = AuthenticatedAppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMemoryChallengeRoute =
  AuthenticatedAppMemoryChallengeRouteImport.update({
    id: '/memory-challenge',
    path: '/memory-challenge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMemoriesRoute =
  AuthenticatedAppMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeRoute = AuthenticatedAppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLoveQuizRoute =
  AuthenticatedAppLoveQuizRouteImport.update({
    id: '/love-quiz',
    path: '/love-quiz',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInviteRoute = AuthenticatedAppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFriendsRoute = AuthenticatedAppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDailyChallengeRoute =
  AuthenticatedAppDailyChallengeRouteImport.update({
    id: '/daily-challenge',
    path: '/daily-challenge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnniversaryRoute =
  AuthenticatedAppAnniversaryRouteImport.update({
    id: '/anniversary',
    path: '/anniversary',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMoviesIndexRoute =
  AuthenticatedAppMoviesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMoviesRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppMoviesIdRoute =
  AuthenticatedAppMoviesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMoviesRoute,
  } as any)
const AuthenticatedAppGamesGameRoute =
  AuthenticatedAppGamesGameRouteImport.update({
    id: '/games/$game',
    path: '/games/$game',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatPeerIdRoute =
  AuthenticatedAppChatPeerIdRouteImport.update({
    id: '/chat/$peerId',
    path: '/chat/$peerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCallPeerIdRoute =
  AuthenticatedAppCallPeerIdRouteImport.update({
    id: '/call/$peerId',
    path: '/call/$peerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMoviesIdWatchRoute =
  AuthenticatedAppMoviesIdWatchRouteImport.update({
    id: '/watch',
    path: '/watch',
    getParentRoute: () => AuthenticatedAppMoviesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/invite': typeof AuthenticatedAppInviteRoute
  '/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/app/me': typeof AuthenticatedAppMeRoute
  '/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/app/mood': typeof AuthenticatedAppMoodRoute
  '/app/movies': typeof AuthenticatedAppMoviesRouteWithChildren
  '/app/paint': typeof AuthenticatedAppPaintRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/play': typeof AuthenticatedAppPlayRoute
  '/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/app/watch': typeof AuthenticatedAppWatchRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/movies/': typeof AuthenticatedAppMoviesIndexRoute
  '/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/invite': typeof AuthenticatedAppInviteRoute
  '/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/app/me': typeof AuthenticatedAppMeRoute
  '/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/app/mood': typeof AuthenticatedAppMoodRoute
  '/app/paint': typeof AuthenticatedAppPaintRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/play': typeof AuthenticatedAppPlayRoute
  '/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/app/watch': typeof AuthenticatedAppWatchRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/movies': typeof AuthenticatedAppMoviesIndexRoute
  '/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/_authenticated/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/_authenticated/app/friends': typeof AuthenticatedAppFriendsRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/invite': typeof AuthenticatedAppInviteRoute
  '/_authenticated/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/_authenticated/app/me': typeof AuthenticatedAppMeRoute
  '/_authenticated/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/_authenticated/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/_authenticated/app/mood': typeof AuthenticatedAppMoodRoute
  '/_authenticated/app/movies': typeof AuthenticatedAppMoviesRouteWithChildren
  '/_authenticated/app/paint': typeof AuthenticatedAppPaintRoute
  '/_authenticated/app/partner': typeof AuthenticatedAppPartnerRoute
  '/_authenticated/app/play': typeof AuthenticatedAppPlayRoute
  '/_authenticated/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/_authenticated/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/_authenticated/app/watch': typeof AuthenticatedAppWatchRoute
  '/_authenticated/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/_authenticated/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/_authenticated/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/_authenticated/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/movies/': typeof AuthenticatedAppMoviesIndexRoute
  '/_authenticated/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin'
    | '/app/anniversary'
    | '/app/daily-challenge'
    | '/app/friends'
    | '/app/help'
    | '/app/invite'
    | '/app/love-quiz'
    | '/app/me'
    | '/app/memories'
    | '/app/memory-challenge'
    | '/app/mood'
    | '/app/movies'
    | '/app/paint'
    | '/app/partner'
    | '/app/play'
    | '/app/puzzle'
    | '/app/scribble'
    | '/app/watch'
    | '/app/wishlist'
    | '/app/'
    | '/app/call/$peerId'
    | '/app/chat/$peerId'
    | '/app/games/$game'
    | '/app/movies/$id'
    | '/lovable/email/queue/process'
    | '/app/chat/'
    | '/app/movies/'
    | '/app/movies/$id/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/anniversary'
    | '/app/daily-challenge'
    | '/app/friends'
    | '/app/help'
    | '/app/invite'
    | '/app/love-quiz'
    | '/app/me'
    | '/app/memories'
    | '/app/memory-challenge'
    | '/app/mood'
    | '/app/paint'
    | '/app/partner'
    | '/app/play'
    | '/app/puzzle'
    | '/app/scribble'
    | '/app/watch'
    | '/app/wishlist'
    | '/app'
    | '/app/call/$peerId'
    | '/app/chat/$peerId'
    | '/app/games/$game'
    | '/app/movies/$id'
    | '/lovable/email/queue/process'
    | '/app/chat'
    | '/app/movies'
    | '/app/movies/$id/watch'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/anniversary'
    | '/_authenticated/app/daily-challenge'
    | '/_authenticated/app/friends'
    | '/_authenticated/app/help'
    | '/_authenticated/app/invite'
    | '/_authenticated/app/love-quiz'
    | '/_authenticated/app/me'
    | '/_authenticated/app/memories'
    | '/_authenticated/app/memory-challenge'
    | '/_authenticated/app/mood'
    | '/_authenticated/app/movies'
    | '/_authenticated/app/paint'
    | '/_authenticated/app/partner'
    | '/_authenticated/app/play'
    | '/_authenticated/app/puzzle'
    | '/_authenticated/app/scribble'
    | '/_authenticated/app/watch'
    | '/_authenticated/app/wishlist'
    | '/_authenticated/app/'
    | '/_authenticated/app/call/$peerId'
    | '/_authenticated/app/chat/$peerId'
    | '/_authenticated/app/games/$game'
    | '/_authenticated/app/movies/$id'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/movies/'
    | '/_authenticated/app/movies/$id/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wishlist': {
      id: '/_authenticated/app/wishlist'
      path: '/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AuthenticatedAppWishlistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/watch': {
      id: '/_authenticated/app/watch'
      path: '/watch'
      fullPath: '/app/watch'
      preLoaderRoute: typeof AuthenticatedAppWatchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scribble': {
      id: '/_authenticated/app/scribble'
      path: '/scribble'
      fullPath: '/app/scribble'
      preLoaderRoute: typeof AuthenticatedAppScribbleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/puzzle': {
      id: '/_authenticated/app/puzzle'
      path: '/puzzle'
      fullPath: '/app/puzzle'
      preLoaderRoute: typeof AuthenticatedAppPuzzleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/play': {
      id: '/_authenticated/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AuthenticatedAppPlayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/partner': {
      id: '/_authenticated/app/partner'
      path: '/partner'
      fullPath: '/app/partner'
      preLoaderRoute: typeof AuthenticatedAppPartnerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/paint': {
      id: '/_authenticated/app/paint'
      path: '/paint'
      fullPath: '/app/paint'
      preLoaderRoute: typeof AuthenticatedAppPaintRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies': {
      id: '/_authenticated/app/movies'
      path: '/movies'
      fullPath: '/app/movies'
      preLoaderRoute: typeof AuthenticatedAppMoviesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mood': {
      id: '/_authenticated/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AuthenticatedAppMoodRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory-challenge': {
      id: '/_authenticated/app/memory-challenge'
      path: '/memory-challenge'
      fullPath: '/app/memory-challenge'
      preLoaderRoute: typeof AuthenticatedAppMemoryChallengeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memories': {
      id: '/_authenticated/app/memories'
      path: '/memories'
      fullPath: '/app/memories'
      preLoaderRoute: typeof AuthenticatedAppMemoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/me': {
      id: '/_authenticated/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AuthenticatedAppMeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/love-quiz': {
      id: '/_authenticated/app/love-quiz'
      path: '/love-quiz'
      fullPath: '/app/love-quiz'
      preLoaderRoute: typeof AuthenticatedAppLoveQuizRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invite': {
      id: '/_authenticated/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AuthenticatedAppInviteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/friends': {
      id: '/_authenticated/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AuthenticatedAppFriendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/daily-challenge': {
      id: '/_authenticated/app/daily-challenge'
      path: '/daily-challenge'
      fullPath: '/app/daily-challenge'
      preLoaderRoute: typeof AuthenticatedAppDailyChallengeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/anniversary': {
      id: '/_authenticated/app/anniversary'
      path: '/anniversary'
      fullPath: '/app/anniversary'
      preLoaderRoute: typeof AuthenticatedAppAnniversaryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies/': {
      id: '/_authenticated/app/movies/'
      path: '/'
      fullPath: '/app/movies/'
      preLoaderRoute: typeof AuthenticatedAppMoviesIndexRouteImport
      parentRoute: typeof AuthenticatedAppMoviesRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/movies/$id': {
      id: '/_authenticated/app/movies/$id'
      path: '/$id'
      fullPath: '/app/movies/$id'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdRouteImport
      parentRoute: typeof AuthenticatedAppMoviesRoute
    }
    '/_authenticated/app/games/$game': {
      id: '/_authenticated/app/games/$game'
      path: '/games/$game'
      fullPath: '/app/games/$game'
      preLoaderRoute: typeof AuthenticatedAppGamesGameRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$peerId': {
      id: '/_authenticated/app/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/app/chat/$peerId'
      preLoaderRoute: typeof AuthenticatedAppChatPeerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/call/$peerId': {
      id: '/_authenticated/app/call/$peerId'
      path: '/call/$peerId'
      fullPath: '/app/call/$peerId'
      preLoaderRoute: typeof AuthenticatedAppCallPeerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies/$id/watch': {
      id: '/_authenticated/app/movies/$id/watch'
      path: '/watch'
      fullPath: '/app/movies/$id/watch'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdWatchRouteImport
      parentRoute: typeof AuthenticatedAppMoviesIdRoute
    }
  }
}

interface AuthenticatedAppMoviesIdRouteChildren {
  AuthenticatedAppMoviesIdWatchRoute: typeof AuthenticatedAppMoviesIdWatchRoute
}

const AuthenticatedAppMoviesIdRouteChildren: AuthenticatedAppMoviesIdRouteChildren =
  {
    AuthenticatedAppMoviesIdWatchRoute: AuthenticatedAppMoviesIdWatchRoute,
  }

const AuthenticatedAppMoviesIdRouteWithChildren =
  AuthenticatedAppMoviesIdRoute._addFileChildren(
    AuthenticatedAppMoviesIdRouteChildren,
  )

interface AuthenticatedAppMoviesRouteChildren {
  AuthenticatedAppMoviesIdRoute: typeof AuthenticatedAppMoviesIdRouteWithChildren
  AuthenticatedAppMoviesIndexRoute: typeof AuthenticatedAppMoviesIndexRoute
}

const AuthenticatedAppMoviesRouteChildren: AuthenticatedAppMoviesRouteChildren =
  {
    AuthenticatedAppMoviesIdRoute: AuthenticatedAppMoviesIdRouteWithChildren,
    AuthenticatedAppMoviesIndexRoute: AuthenticatedAppMoviesIndexRoute,
  }

const AuthenticatedAppMoviesRouteWithChildren =
  AuthenticatedAppMoviesRoute._addFileChildren(
    AuthenticatedAppMoviesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAnniversaryRoute: typeof AuthenticatedAppAnniversaryRoute
  AuthenticatedAppDailyChallengeRoute: typeof AuthenticatedAppDailyChallengeRoute
  AuthenticatedAppFriendsRoute: typeof AuthenticatedAppFriendsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppInviteRoute: typeof AuthenticatedAppInviteRoute
  AuthenticatedAppLoveQuizRoute: typeof AuthenticatedAppLoveQuizRoute
  AuthenticatedAppMeRoute: typeof AuthenticatedAppMeRoute
  AuthenticatedAppMemoriesRoute: typeof AuthenticatedAppMemoriesRoute
  AuthenticatedAppMemoryChallengeRoute: typeof AuthenticatedAppMemoryChallengeRoute
  AuthenticatedAppMoodRoute: typeof AuthenticatedAppMoodRoute
  AuthenticatedAppMoviesRoute: typeof AuthenticatedAppMoviesRouteWithChildren
  AuthenticatedAppPaintRoute: typeof AuthenticatedAppPaintRoute
  AuthenticatedAppPartnerRoute: typeof AuthenticatedAppPartnerRoute
  AuthenticatedAppPlayRoute: typeof AuthenticatedAppPlayRoute
  AuthenticatedAppPuzzleRoute: typeof AuthenticatedAppPuzzleRoute
  AuthenticatedAppScribbleRoute: typeof AuthenticatedAppScribbleRoute
  AuthenticatedAppWatchRoute: typeof AuthenticatedAppWatchRoute
  AuthenticatedAppWishlistRoute: typeof AuthenticatedAppWishlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCallPeerIdRoute: typeof AuthenticatedAppCallPeerIdRoute
  AuthenticatedAppChatPeerIdRoute: typeof AuthenticatedAppChatPeerIdRoute
  AuthenticatedAppGamesGameRoute: typeof AuthenticatedAppGamesGameRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAnniversaryRoute: AuthenticatedAppAnniversaryRoute,
  AuthenticatedAppDailyChallengeRoute: AuthenticatedAppDailyChallengeRoute,
  AuthenticatedAppFriendsRoute: AuthenticatedAppFriendsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppInviteRoute: AuthenticatedAppInviteRoute,
  AuthenticatedAppLoveQuizRoute: AuthenticatedAppLoveQuizRoute,
  AuthenticatedAppMeRoute: AuthenticatedAppMeRoute,
  AuthenticatedAppMemoriesRoute: AuthenticatedAppMemoriesRoute,
  AuthenticatedAppMemoryChallengeRoute: AuthenticatedAppMemoryChallengeRoute,
  AuthenticatedAppMoodRoute: AuthenticatedAppMoodRoute,
  AuthenticatedAppMoviesRoute: AuthenticatedAppMoviesRouteWithChildren,
  AuthenticatedAppPaintRoute: AuthenticatedAppPaintRoute,
  AuthenticatedAppPartnerRoute: AuthenticatedAppPartnerRoute,
  AuthenticatedAppPlayRoute: AuthenticatedAppPlayRoute,
  AuthenticatedAppPuzzleRoute: AuthenticatedAppPuzzleRoute,
  AuthenticatedAppScribbleRoute: AuthenticatedAppScribbleRoute,
  AuthenticatedAppWatchRoute: AuthenticatedAppWatchRoute,
  AuthenticatedAppWishlistRoute: AuthenticatedAppWishlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCallPeerIdRoute: AuthenticatedAppCallPeerIdRoute,
  AuthenticatedAppChatPeerIdRoute: AuthenticatedAppChatPeerIdRoute,
  AuthenticatedAppGamesGameRoute: AuthenticatedAppGamesGameRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
