/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiLivekitTokenRouteImport } from './routes/api/livekit-token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as AuthenticatedAppWishlistRouteImport } from './routes/_authenticated/app.wishlist'
import { Route as AuthenticatedAppWatchlistRouteImport } from './routes/_authenticated/app.watchlist'
import { Route as AuthenticatedAppWatchRouteImport } from './routes/_authenticated/app.watch'
import { Route as AuthenticatedAppUnoRouteImport } from './routes/_authenticated/app.uno'
import { Route as AuthenticatedAppTriviaRouteImport } from './routes/_authenticated/app.trivia'
import { Route as AuthenticatedAppTimelineRouteImport } from './routes/_authenticated/app.timeline'
import { Route as AuthenticatedAppTamannaRouteImport } from './routes/_authenticated/app.tamanna'
import { Route as AuthenticatedAppShopRouteImport } from './routes/_authenticated/app.shop'
import { Route as AuthenticatedAppScribbleRouteImport } from './routes/_authenticated/app.scribble'
import { Route as AuthenticatedAppRitualsRouteImport } from './routes/_authenticated/app.rituals'
import { Route as AuthenticatedAppPuzzleRouteImport } from './routes/_authenticated/app.puzzle'
import { Route as AuthenticatedAppPoolRouteImport } from './routes/_authenticated/app.pool'
import { Route as AuthenticatedAppPlayRouteImport } from './routes/_authenticated/app.play'
import { Route as AuthenticatedAppPartnerRouteImport } from './routes/_authenticated/app.partner'
import { Route as AuthenticatedAppPaintRouteImport } from './routes/_authenticated/app.paint'
import { Route as AuthenticatedAppMoviesRouteImport } from './routes/_authenticated/app.movies'
import { Route as AuthenticatedAppMoodRouteImport } from './routes/_authenticated/app.mood'
import { Route as AuthenticatedAppMemoryChallengeRouteImport } from './routes/_authenticated/app.memory-challenge'
import { Route as AuthenticatedAppMemoriesRouteImport } from './routes/_authenticated/app.memories'
import { Route as AuthenticatedAppMeRouteImport } from './routes/_authenticated/app.me'
import { Route as AuthenticatedAppLudoRouteImport } from './routes/_authenticated/app.ludo'
import { Route as AuthenticatedAppLoveQuizRouteImport } from './routes/_authenticated/app.love-quiz'
import { Route as AuthenticatedAppKnowmeRouteImport } from './routes/_authenticated/app.knowme'
import { Route as AuthenticatedAppJournalRouteImport } from './routes/_authenticated/app.journal'
import { Route as AuthenticatedAppInviteRouteImport } from './routes/_authenticated/app.invite'
import { Route as AuthenticatedAppHideseekRouteImport } from './routes/_authenticated/app.hideseek'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppFriendsRouteImport } from './routes/_authenticated/app.friends'
import { Route as AuthenticatedAppDailyChallengeRouteImport } from './routes/_authenticated/app.daily-challenge'
import { Route as AuthenticatedAppCouponsRouteImport } from './routes/_authenticated/app.coupons'
import { Route as AuthenticatedAppConstellationRouteImport } from './routes/_authenticated/app.constellation'
import { Route as AuthenticatedAppConciergeRouteImport } from './routes/_authenticated/app.concierge'
import { Route as AuthenticatedAppChessRouteImport } from './routes/_authenticated/app.chess'
import { Route as AuthenticatedAppCallsRouteImport } from './routes/_authenticated/app.calls'
import { Route as AuthenticatedAppBucketRouteImport } from './routes/_authenticated/app.bucket'
import { Route as AuthenticatedAppAnniversaryRouteImport } from './routes/_authenticated/app.anniversary'
import { Route as AuthenticatedAppMoviesIndexRouteImport } from './routes/_authenticated/app.movies.index'
import { Route as AuthenticatedAppLettersIndexRouteImport } from './routes/_authenticated/app.letters.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAppUserUserIdRouteImport } from './routes/_authenticated/app.user.$userId'
import { Route as AuthenticatedAppMoviesListRouteImport } from './routes/_authenticated/app.movies.list'
import { Route as AuthenticatedAppMoviesIdRouteImport } from './routes/_authenticated/app.movies.$id'
import { Route as AuthenticatedAppLettersIdRouteImport } from './routes/_authenticated/app.letters.$id'
import { Route as AuthenticatedAppGroupMatchMatchIdRouteImport } from './routes/_authenticated/app.group-match.$matchId'
import { Route as AuthenticatedAppGamesGameRouteImport } from './routes/_authenticated/app.games.$game'
import { Route as AuthenticatedAppChatPeerIdRouteImport } from './routes/_authenticated/app.chat.$peerId'
import { Route as AuthenticatedAppCallPeerIdRouteImport } from './routes/_authenticated/app.call.$peerId'
import { Route as AuthenticatedAppMoviesIdWatchRouteImport } from './routes/_authenticated/app.movies.$id.watch'
import { Route as AuthenticatedAppMoviesIdPartyRouteImport } from './routes/_authenticated/app.movies.$id.party'
import { Route as AuthenticatedAppChatGroupGroupIdRouteImport } from './routes/_authenticated/app.chat.group.$groupId'
import { Route as AuthenticatedAppCallGroupGroupIdRouteImport } from './routes/_authenticated/app.call.group.$groupId'
import { Route as AuthenticatedAppChatGroupGroupIdIndexRouteImport } from './routes/_authenticated/app.chat.group.$groupId.index'
import { Route as AuthenticatedAppChatGroupGroupIdSettingsRouteImport } from './routes/_authenticated/app.chat.group.$groupId.settings'
import { Route as AuthenticatedAppChatGroupGroupIdInfoRouteImport } from './routes/_authenticated/app.chat.group.$groupId.info'
import { Route as AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRouteImport } from './routes/_authenticated/app.movies.$id.episode.$season.$episode'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitTokenRoute = ApiLivekitTokenRouteImport.update({
  id: '/api/livekit-token',
  path: '/api/livekit-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWishlistRoute =
  AuthenticatedAppWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWatchlistRoute =
  AuthenticatedAppWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWatchRoute = AuthenticatedAppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUnoRoute = AuthenticatedAppUnoRouteImport.update({
  id: '/uno',
  path: '/uno',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTriviaRoute = AuthenticatedAppTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTimelineRoute =
  AuthenticatedAppTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTamannaRoute = AuthenticatedAppTamannaRouteImport.update({
  id: '/tamanna',
  path: '/tamanna',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppShopRoute = AuthenticatedAppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScribbleRoute =
  AuthenticatedAppScribbleRouteImport.update({
    id: '/scribble',
    path: '/scribble',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRitualsRoute = AuthenticatedAppRitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPuzzleRoute = AuthenticatedAppPuzzleRouteImport.update({
  id: '/puzzle',
  path: '/puzzle',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPoolRoute = AuthenticatedAppPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlayRoute = AuthenticatedAppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPartnerRoute = AuthenticatedAppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaintRoute = AuthenticatedAppPaintRouteImport.update({
  id: '/paint',
  path: '/paint',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMoviesRoute = AuthenticatedAppMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMoodRoute = AuthenticatedAppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMemoryChallengeRoute =
  AuthenticatedAppMemoryChallengeRouteImport.update({
    id: '/memory-challenge',
    path: '/memory-challenge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMemoriesRoute =
  AuthenticatedAppMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeRoute = AuthenticatedAppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLudoRoute = AuthenticatedAppLudoRouteImport.update({
  id: '/ludo',
  path: '/ludo',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLoveQuizRoute =
  AuthenticatedAppLoveQuizRouteImport.update({
    id: '/love-quiz',
    path: '/love-quiz',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKnowmeRoute = AuthenticatedAppKnowmeRouteImport.update({
  id: '/knowme',
  path: '/knowme',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJournalRoute = AuthenticatedAppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInviteRoute = AuthenticatedAppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHideseekRoute =
  AuthenticatedAppHideseekRouteImport.update({
    id: '/hideseek',
    path: '/hideseek',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFriendsRoute = AuthenticatedAppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDailyChallengeRoute =
  AuthenticatedAppDailyChallengeRouteImport.update({
    id: '/daily-challenge',
    path: '/daily-challenge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCouponsRoute = AuthenticatedAppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConstellationRoute =
  AuthenticatedAppConstellationRouteImport.update({
    id: '/constellation',
    path: '/constellation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConciergeRoute =
  AuthenticatedAppConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChessRoute = AuthenticatedAppChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCallsRoute = AuthenticatedAppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBucketRoute = AuthenticatedAppBucketRouteImport.update({
  id: '/bucket',
  path: '/bucket',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnniversaryRoute =
  AuthenticatedAppAnniversaryRouteImport.update({
    id: '/anniversary',
    path: '/anniversary',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMoviesIndexRoute =
  AuthenticatedAppMoviesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMoviesRoute,
  } as any)
const AuthenticatedAppLettersIndexRoute =
  AuthenticatedAppLettersIndexRouteImport.update({
    id: '/letters/',
    path: '/letters/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppUserUserIdRoute =
  AuthenticatedAppUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMoviesListRoute =
  AuthenticatedAppMoviesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedAppMoviesRoute,
  } as any)
const AuthenticatedAppMoviesIdRoute =
  AuthenticatedAppMoviesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMoviesRoute,
  } as any)
const AuthenticatedAppLettersIdRoute =
  AuthenticatedAppLettersIdRouteImport.update({
    id: '/letters/$id',
    path: '/letters/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupMatchMatchIdRoute =
  AuthenticatedAppGroupMatchMatchIdRouteImport.update({
    id: '/group-match/$matchId',
    path: '/group-match/$matchId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGamesGameRoute =
  AuthenticatedAppGamesGameRouteImport.update({
    id: '/games/$game',
    path: '/games/$game',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatPeerIdRoute =
  AuthenticatedAppChatPeerIdRouteImport.update({
    id: '/chat/$peerId',
    path: '/chat/$peerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCallPeerIdRoute =
  AuthenticatedAppCallPeerIdRouteImport.update({
    id: '/call/$peerId',
    path: '/call/$peerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMoviesIdWatchRoute =
  AuthenticatedAppMoviesIdWatchRouteImport.update({
    id: '/watch',
    path: '/watch',
    getParentRoute: () => AuthenticatedAppMoviesIdRoute,
  } as any)
const AuthenticatedAppMoviesIdPartyRoute =
  AuthenticatedAppMoviesIdPartyRouteImport.update({
    id: '/party',
    path: '/party',
    getParentRoute: () => AuthenticatedAppMoviesIdRoute,
  } as any)
const AuthenticatedAppChatGroupGroupIdRoute =
  AuthenticatedAppChatGroupGroupIdRouteImport.update({
    id: '/chat/group/$groupId',
    path: '/chat/group/$groupId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCallGroupGroupIdRoute =
  AuthenticatedAppCallGroupGroupIdRouteImport.update({
    id: '/call/group/$groupId',
    path: '/call/group/$groupId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatGroupGroupIdIndexRoute =
  AuthenticatedAppChatGroupGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatGroupGroupIdRoute,
  } as any)
const AuthenticatedAppChatGroupGroupIdSettingsRoute =
  AuthenticatedAppChatGroupGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppChatGroupGroupIdRoute,
  } as any)
const AuthenticatedAppChatGroupGroupIdInfoRoute =
  AuthenticatedAppChatGroupGroupIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthenticatedAppChatGroupGroupIdRoute,
  } as any)
const AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute =
  AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRouteImport.update({
    id: '/episode/$season/$episode',
    path: '/episode/$season/$episode',
    getParentRoute: () => AuthenticatedAppMoviesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/app/bucket': typeof AuthenticatedAppBucketRoute
  '/app/calls': typeof AuthenticatedAppCallsRoute
  '/app/chess': typeof AuthenticatedAppChessRoute
  '/app/concierge': typeof AuthenticatedAppConciergeRoute
  '/app/constellation': typeof AuthenticatedAppConstellationRoute
  '/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/hideseek': typeof AuthenticatedAppHideseekRoute
  '/app/invite': typeof AuthenticatedAppInviteRoute
  '/app/journal': typeof AuthenticatedAppJournalRoute
  '/app/knowme': typeof AuthenticatedAppKnowmeRoute
  '/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/app/ludo': typeof AuthenticatedAppLudoRoute
  '/app/me': typeof AuthenticatedAppMeRoute
  '/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/app/mood': typeof AuthenticatedAppMoodRoute
  '/app/movies': typeof AuthenticatedAppMoviesRouteWithChildren
  '/app/paint': typeof AuthenticatedAppPaintRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/play': typeof AuthenticatedAppPlayRoute
  '/app/pool': typeof AuthenticatedAppPoolRoute
  '/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/app/rituals': typeof AuthenticatedAppRitualsRoute
  '/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/tamanna': typeof AuthenticatedAppTamannaRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/trivia': typeof AuthenticatedAppTriviaRoute
  '/app/uno': typeof AuthenticatedAppUnoRoute
  '/app/watch': typeof AuthenticatedAppWatchRoute
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/app/group-match/$matchId': typeof AuthenticatedAppGroupMatchMatchIdRoute
  '/app/letters/$id': typeof AuthenticatedAppLettersIdRoute
  '/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/app/movies/list': typeof AuthenticatedAppMoviesListRoute
  '/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/letters/': typeof AuthenticatedAppLettersIndexRoute
  '/app/movies/': typeof AuthenticatedAppMoviesIndexRoute
  '/app/call/group/$groupId': typeof AuthenticatedAppCallGroupGroupIdRoute
  '/app/chat/group/$groupId': typeof AuthenticatedAppChatGroupGroupIdRouteWithChildren
  '/app/movies/$id/party': typeof AuthenticatedAppMoviesIdPartyRoute
  '/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
  '/app/chat/group/$groupId/info': typeof AuthenticatedAppChatGroupGroupIdInfoRoute
  '/app/chat/group/$groupId/settings': typeof AuthenticatedAppChatGroupGroupIdSettingsRoute
  '/app/chat/group/$groupId/': typeof AuthenticatedAppChatGroupGroupIdIndexRoute
  '/app/movies/$id/episode/$season/$episode': typeof AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/app/bucket': typeof AuthenticatedAppBucketRoute
  '/app/calls': typeof AuthenticatedAppCallsRoute
  '/app/chess': typeof AuthenticatedAppChessRoute
  '/app/concierge': typeof AuthenticatedAppConciergeRoute
  '/app/constellation': typeof AuthenticatedAppConstellationRoute
  '/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/hideseek': typeof AuthenticatedAppHideseekRoute
  '/app/invite': typeof AuthenticatedAppInviteRoute
  '/app/journal': typeof AuthenticatedAppJournalRoute
  '/app/knowme': typeof AuthenticatedAppKnowmeRoute
  '/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/app/ludo': typeof AuthenticatedAppLudoRoute
  '/app/me': typeof AuthenticatedAppMeRoute
  '/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/app/mood': typeof AuthenticatedAppMoodRoute
  '/app/paint': typeof AuthenticatedAppPaintRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/play': typeof AuthenticatedAppPlayRoute
  '/app/pool': typeof AuthenticatedAppPoolRoute
  '/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/app/rituals': typeof AuthenticatedAppRitualsRoute
  '/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/tamanna': typeof AuthenticatedAppTamannaRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/trivia': typeof AuthenticatedAppTriviaRoute
  '/app/uno': typeof AuthenticatedAppUnoRoute
  '/app/watch': typeof AuthenticatedAppWatchRoute
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/app/group-match/$matchId': typeof AuthenticatedAppGroupMatchMatchIdRoute
  '/app/letters/$id': typeof AuthenticatedAppLettersIdRoute
  '/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/app/movies/list': typeof AuthenticatedAppMoviesListRoute
  '/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/letters': typeof AuthenticatedAppLettersIndexRoute
  '/app/movies': typeof AuthenticatedAppMoviesIndexRoute
  '/app/call/group/$groupId': typeof AuthenticatedAppCallGroupGroupIdRoute
  '/app/movies/$id/party': typeof AuthenticatedAppMoviesIdPartyRoute
  '/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
  '/app/chat/group/$groupId/info': typeof AuthenticatedAppChatGroupGroupIdInfoRoute
  '/app/chat/group/$groupId/settings': typeof AuthenticatedAppChatGroupGroupIdSettingsRoute
  '/app/chat/group/$groupId': typeof AuthenticatedAppChatGroupGroupIdIndexRoute
  '/app/movies/$id/episode/$season/$episode': typeof AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/app/anniversary': typeof AuthenticatedAppAnniversaryRoute
  '/_authenticated/app/bucket': typeof AuthenticatedAppBucketRoute
  '/_authenticated/app/calls': typeof AuthenticatedAppCallsRoute
  '/_authenticated/app/chess': typeof AuthenticatedAppChessRoute
  '/_authenticated/app/concierge': typeof AuthenticatedAppConciergeRoute
  '/_authenticated/app/constellation': typeof AuthenticatedAppConstellationRoute
  '/_authenticated/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/_authenticated/app/daily-challenge': typeof AuthenticatedAppDailyChallengeRoute
  '/_authenticated/app/friends': typeof AuthenticatedAppFriendsRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/hideseek': typeof AuthenticatedAppHideseekRoute
  '/_authenticated/app/invite': typeof AuthenticatedAppInviteRoute
  '/_authenticated/app/journal': typeof AuthenticatedAppJournalRoute
  '/_authenticated/app/knowme': typeof AuthenticatedAppKnowmeRoute
  '/_authenticated/app/love-quiz': typeof AuthenticatedAppLoveQuizRoute
  '/_authenticated/app/ludo': typeof AuthenticatedAppLudoRoute
  '/_authenticated/app/me': typeof AuthenticatedAppMeRoute
  '/_authenticated/app/memories': typeof AuthenticatedAppMemoriesRoute
  '/_authenticated/app/memory-challenge': typeof AuthenticatedAppMemoryChallengeRoute
  '/_authenticated/app/mood': typeof AuthenticatedAppMoodRoute
  '/_authenticated/app/movies': typeof AuthenticatedAppMoviesRouteWithChildren
  '/_authenticated/app/paint': typeof AuthenticatedAppPaintRoute
  '/_authenticated/app/partner': typeof AuthenticatedAppPartnerRoute
  '/_authenticated/app/play': typeof AuthenticatedAppPlayRoute
  '/_authenticated/app/pool': typeof AuthenticatedAppPoolRoute
  '/_authenticated/app/puzzle': typeof AuthenticatedAppPuzzleRoute
  '/_authenticated/app/rituals': typeof AuthenticatedAppRitualsRoute
  '/_authenticated/app/scribble': typeof AuthenticatedAppScribbleRoute
  '/_authenticated/app/shop': typeof AuthenticatedAppShopRoute
  '/_authenticated/app/tamanna': typeof AuthenticatedAppTamannaRoute
  '/_authenticated/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/_authenticated/app/trivia': typeof AuthenticatedAppTriviaRoute
  '/_authenticated/app/uno': typeof AuthenticatedAppUnoRoute
  '/_authenticated/app/watch': typeof AuthenticatedAppWatchRoute
  '/_authenticated/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/_authenticated/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/call/$peerId': typeof AuthenticatedAppCallPeerIdRoute
  '/_authenticated/app/chat/$peerId': typeof AuthenticatedAppChatPeerIdRoute
  '/_authenticated/app/games/$game': typeof AuthenticatedAppGamesGameRoute
  '/_authenticated/app/group-match/$matchId': typeof AuthenticatedAppGroupMatchMatchIdRoute
  '/_authenticated/app/letters/$id': typeof AuthenticatedAppLettersIdRoute
  '/_authenticated/app/movies/$id': typeof AuthenticatedAppMoviesIdRouteWithChildren
  '/_authenticated/app/movies/list': typeof AuthenticatedAppMoviesListRoute
  '/_authenticated/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/letters/': typeof AuthenticatedAppLettersIndexRoute
  '/_authenticated/app/movies/': typeof AuthenticatedAppMoviesIndexRoute
  '/_authenticated/app/call/group/$groupId': typeof AuthenticatedAppCallGroupGroupIdRoute
  '/_authenticated/app/chat/group/$groupId': typeof AuthenticatedAppChatGroupGroupIdRouteWithChildren
  '/_authenticated/app/movies/$id/party': typeof AuthenticatedAppMoviesIdPartyRoute
  '/_authenticated/app/movies/$id/watch': typeof AuthenticatedAppMoviesIdWatchRoute
  '/_authenticated/app/chat/group/$groupId/info': typeof AuthenticatedAppChatGroupGroupIdInfoRoute
  '/_authenticated/app/chat/group/$groupId/settings': typeof AuthenticatedAppChatGroupGroupIdSettingsRoute
  '/_authenticated/app/chat/group/$groupId/': typeof AuthenticatedAppChatGroupGroupIdIndexRoute
  '/_authenticated/app/movies/$id/episode/$season/$episode': typeof AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/features'
    | '/privacy'
    | '/reset-password'
    | '/showcase'
    | '/terms'
    | '/unsubscribe'
    | '/app'
    | '/api/livekit-token'
    | '/email/unsubscribe'
    | '/app/anniversary'
    | '/app/bucket'
    | '/app/calls'
    | '/app/chess'
    | '/app/concierge'
    | '/app/constellation'
    | '/app/coupons'
    | '/app/daily-challenge'
    | '/app/friends'
    | '/app/help'
    | '/app/hideseek'
    | '/app/invite'
    | '/app/journal'
    | '/app/knowme'
    | '/app/love-quiz'
    | '/app/ludo'
    | '/app/me'
    | '/app/memories'
    | '/app/memory-challenge'
    | '/app/mood'
    | '/app/movies'
    | '/app/paint'
    | '/app/partner'
    | '/app/play'
    | '/app/pool'
    | '/app/puzzle'
    | '/app/rituals'
    | '/app/scribble'
    | '/app/shop'
    | '/app/tamanna'
    | '/app/timeline'
    | '/app/trivia'
    | '/app/uno'
    | '/app/watch'
    | '/app/watchlist'
    | '/app/wishlist'
    | '/api/public/push-dispatch'
    | '/lovable/email/suppression'
    | '/app/'
    | '/app/call/$peerId'
    | '/app/chat/$peerId'
    | '/app/games/$game'
    | '/app/group-match/$matchId'
    | '/app/letters/$id'
    | '/app/movies/$id'
    | '/app/movies/list'
    | '/app/user/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/chat/'
    | '/app/letters/'
    | '/app/movies/'
    | '/app/call/group/$groupId'
    | '/app/chat/group/$groupId'
    | '/app/movies/$id/party'
    | '/app/movies/$id/watch'
    | '/app/chat/group/$groupId/info'
    | '/app/chat/group/$groupId/settings'
    | '/app/chat/group/$groupId/'
    | '/app/movies/$id/episode/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/privacy'
    | '/reset-password'
    | '/showcase'
    | '/terms'
    | '/unsubscribe'
    | '/api/livekit-token'
    | '/email/unsubscribe'
    | '/app/anniversary'
    | '/app/bucket'
    | '/app/calls'
    | '/app/chess'
    | '/app/concierge'
    | '/app/constellation'
    | '/app/coupons'
    | '/app/daily-challenge'
    | '/app/friends'
    | '/app/help'
    | '/app/hideseek'
    | '/app/invite'
    | '/app/journal'
    | '/app/knowme'
    | '/app/love-quiz'
    | '/app/ludo'
    | '/app/me'
    | '/app/memories'
    | '/app/memory-challenge'
    | '/app/mood'
    | '/app/paint'
    | '/app/partner'
    | '/app/play'
    | '/app/pool'
    | '/app/puzzle'
    | '/app/rituals'
    | '/app/scribble'
    | '/app/shop'
    | '/app/tamanna'
    | '/app/timeline'
    | '/app/trivia'
    | '/app/uno'
    | '/app/watch'
    | '/app/watchlist'
    | '/app/wishlist'
    | '/api/public/push-dispatch'
    | '/lovable/email/suppression'
    | '/app'
    | '/app/call/$peerId'
    | '/app/chat/$peerId'
    | '/app/games/$game'
    | '/app/group-match/$matchId'
    | '/app/letters/$id'
    | '/app/movies/$id'
    | '/app/movies/list'
    | '/app/user/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/chat'
    | '/app/letters'
    | '/app/movies'
    | '/app/call/group/$groupId'
    | '/app/movies/$id/party'
    | '/app/movies/$id/watch'
    | '/app/chat/group/$groupId/info'
    | '/app/chat/group/$groupId/settings'
    | '/app/chat/group/$groupId'
    | '/app/movies/$id/episode/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/features'
    | '/privacy'
    | '/reset-password'
    | '/showcase'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/app'
    | '/api/livekit-token'
    | '/email/unsubscribe'
    | '/_authenticated/app/anniversary'
    | '/_authenticated/app/bucket'
    | '/_authenticated/app/calls'
    | '/_authenticated/app/chess'
    | '/_authenticated/app/concierge'
    | '/_authenticated/app/constellation'
    | '/_authenticated/app/coupons'
    | '/_authenticated/app/daily-challenge'
    | '/_authenticated/app/friends'
    | '/_authenticated/app/help'
    | '/_authenticated/app/hideseek'
    | '/_authenticated/app/invite'
    | '/_authenticated/app/journal'
    | '/_authenticated/app/knowme'
    | '/_authenticated/app/love-quiz'
    | '/_authenticated/app/ludo'
    | '/_authenticated/app/me'
    | '/_authenticated/app/memories'
    | '/_authenticated/app/memory-challenge'
    | '/_authenticated/app/mood'
    | '/_authenticated/app/movies'
    | '/_authenticated/app/paint'
    | '/_authenticated/app/partner'
    | '/_authenticated/app/play'
    | '/_authenticated/app/pool'
    | '/_authenticated/app/puzzle'
    | '/_authenticated/app/rituals'
    | '/_authenticated/app/scribble'
    | '/_authenticated/app/shop'
    | '/_authenticated/app/tamanna'
    | '/_authenticated/app/timeline'
    | '/_authenticated/app/trivia'
    | '/_authenticated/app/uno'
    | '/_authenticated/app/watch'
    | '/_authenticated/app/watchlist'
    | '/_authenticated/app/wishlist'
    | '/api/public/push-dispatch'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/_authenticated/app/call/$peerId'
    | '/_authenticated/app/chat/$peerId'
    | '/_authenticated/app/games/$game'
    | '/_authenticated/app/group-match/$matchId'
    | '/_authenticated/app/letters/$id'
    | '/_authenticated/app/movies/$id'
    | '/_authenticated/app/movies/list'
    | '/_authenticated/app/user/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/letters/'
    | '/_authenticated/app/movies/'
    | '/_authenticated/app/call/group/$groupId'
    | '/_authenticated/app/chat/group/$groupId'
    | '/_authenticated/app/movies/$id/party'
    | '/_authenticated/app/movies/$id/watch'
    | '/_authenticated/app/chat/group/$groupId/info'
    | '/_authenticated/app/chat/group/$groupId/settings'
    | '/_authenticated/app/chat/group/$groupId/'
    | '/_authenticated/app/movies/$id/episode/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiLivekitTokenRoute: typeof ApiLivekitTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit-token': {
      id: '/api/livekit-token'
      path: '/api/livekit-token'
      fullPath: '/api/livekit-token'
      preLoaderRoute: typeof ApiLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/wishlist': {
      id: '/_authenticated/app/wishlist'
      path: '/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AuthenticatedAppWishlistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/watchlist': {
      id: '/_authenticated/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AuthenticatedAppWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/watch': {
      id: '/_authenticated/app/watch'
      path: '/watch'
      fullPath: '/app/watch'
      preLoaderRoute: typeof AuthenticatedAppWatchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/uno': {
      id: '/_authenticated/app/uno'
      path: '/uno'
      fullPath: '/app/uno'
      preLoaderRoute: typeof AuthenticatedAppUnoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trivia': {
      id: '/_authenticated/app/trivia'
      path: '/trivia'
      fullPath: '/app/trivia'
      preLoaderRoute: typeof AuthenticatedAppTriviaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/timeline': {
      id: '/_authenticated/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthenticatedAppTimelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tamanna': {
      id: '/_authenticated/app/tamanna'
      path: '/tamanna'
      fullPath: '/app/tamanna'
      preLoaderRoute: typeof AuthenticatedAppTamannaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shop': {
      id: '/_authenticated/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AuthenticatedAppShopRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scribble': {
      id: '/_authenticated/app/scribble'
      path: '/scribble'
      fullPath: '/app/scribble'
      preLoaderRoute: typeof AuthenticatedAppScribbleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rituals': {
      id: '/_authenticated/app/rituals'
      path: '/rituals'
      fullPath: '/app/rituals'
      preLoaderRoute: typeof AuthenticatedAppRitualsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/puzzle': {
      id: '/_authenticated/app/puzzle'
      path: '/puzzle'
      fullPath: '/app/puzzle'
      preLoaderRoute: typeof AuthenticatedAppPuzzleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pool': {
      id: '/_authenticated/app/pool'
      path: '/pool'
      fullPath: '/app/pool'
      preLoaderRoute: typeof AuthenticatedAppPoolRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/play': {
      id: '/_authenticated/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AuthenticatedAppPlayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/partner': {
      id: '/_authenticated/app/partner'
      path: '/partner'
      fullPath: '/app/partner'
      preLoaderRoute: typeof AuthenticatedAppPartnerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/paint': {
      id: '/_authenticated/app/paint'
      path: '/paint'
      fullPath: '/app/paint'
      preLoaderRoute: typeof AuthenticatedAppPaintRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies': {
      id: '/_authenticated/app/movies'
      path: '/movies'
      fullPath: '/app/movies'
      preLoaderRoute: typeof AuthenticatedAppMoviesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mood': {
      id: '/_authenticated/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AuthenticatedAppMoodRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory-challenge': {
      id: '/_authenticated/app/memory-challenge'
      path: '/memory-challenge'
      fullPath: '/app/memory-challenge'
      preLoaderRoute: typeof AuthenticatedAppMemoryChallengeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memories': {
      id: '/_authenticated/app/memories'
      path: '/memories'
      fullPath: '/app/memories'
      preLoaderRoute: typeof AuthenticatedAppMemoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/me': {
      id: '/_authenticated/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AuthenticatedAppMeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ludo': {
      id: '/_authenticated/app/ludo'
      path: '/ludo'
      fullPath: '/app/ludo'
      preLoaderRoute: typeof AuthenticatedAppLudoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/love-quiz': {
      id: '/_authenticated/app/love-quiz'
      path: '/love-quiz'
      fullPath: '/app/love-quiz'
      preLoaderRoute: typeof AuthenticatedAppLoveQuizRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/knowme': {
      id: '/_authenticated/app/knowme'
      path: '/knowme'
      fullPath: '/app/knowme'
      preLoaderRoute: typeof AuthenticatedAppKnowmeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/journal': {
      id: '/_authenticated/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AuthenticatedAppJournalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invite': {
      id: '/_authenticated/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AuthenticatedAppInviteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hideseek': {
      id: '/_authenticated/app/hideseek'
      path: '/hideseek'
      fullPath: '/app/hideseek'
      preLoaderRoute: typeof AuthenticatedAppHideseekRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/friends': {
      id: '/_authenticated/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AuthenticatedAppFriendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/daily-challenge': {
      id: '/_authenticated/app/daily-challenge'
      path: '/daily-challenge'
      fullPath: '/app/daily-challenge'
      preLoaderRoute: typeof AuthenticatedAppDailyChallengeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coupons': {
      id: '/_authenticated/app/coupons'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AuthenticatedAppCouponsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/constellation': {
      id: '/_authenticated/app/constellation'
      path: '/constellation'
      fullPath: '/app/constellation'
      preLoaderRoute: typeof AuthenticatedAppConstellationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/concierge': {
      id: '/_authenticated/app/concierge'
      path: '/concierge'
      fullPath: '/app/concierge'
      preLoaderRoute: typeof AuthenticatedAppConciergeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chess': {
      id: '/_authenticated/app/chess'
      path: '/chess'
      fullPath: '/app/chess'
      preLoaderRoute: typeof AuthenticatedAppChessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calls': {
      id: '/_authenticated/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AuthenticatedAppCallsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bucket': {
      id: '/_authenticated/app/bucket'
      path: '/bucket'
      fullPath: '/app/bucket'
      preLoaderRoute: typeof AuthenticatedAppBucketRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/anniversary': {
      id: '/_authenticated/app/anniversary'
      path: '/anniversary'
      fullPath: '/app/anniversary'
      preLoaderRoute: typeof AuthenticatedAppAnniversaryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies/': {
      id: '/_authenticated/app/movies/'
      path: '/'
      fullPath: '/app/movies/'
      preLoaderRoute: typeof AuthenticatedAppMoviesIndexRouteImport
      parentRoute: typeof AuthenticatedAppMoviesRoute
    }
    '/_authenticated/app/letters/': {
      id: '/_authenticated/app/letters/'
      path: '/letters'
      fullPath: '/app/letters/'
      preLoaderRoute: typeof AuthenticatedAppLettersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/user/$userId': {
      id: '/_authenticated/app/user/$userId'
      path: '/user/$userId'
      fullPath: '/app/user/$userId'
      preLoaderRoute: typeof AuthenticatedAppUserUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies/list': {
      id: '/_authenticated/app/movies/list'
      path: '/list'
      fullPath: '/app/movies/list'
      preLoaderRoute: typeof AuthenticatedAppMoviesListRouteImport
      parentRoute: typeof AuthenticatedAppMoviesRoute
    }
    '/_authenticated/app/movies/$id': {
      id: '/_authenticated/app/movies/$id'
      path: '/$id'
      fullPath: '/app/movies/$id'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdRouteImport
      parentRoute: typeof AuthenticatedAppMoviesRoute
    }
    '/_authenticated/app/letters/$id': {
      id: '/_authenticated/app/letters/$id'
      path: '/letters/$id'
      fullPath: '/app/letters/$id'
      preLoaderRoute: typeof AuthenticatedAppLettersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/group-match/$matchId': {
      id: '/_authenticated/app/group-match/$matchId'
      path: '/group-match/$matchId'
      fullPath: '/app/group-match/$matchId'
      preLoaderRoute: typeof AuthenticatedAppGroupMatchMatchIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/games/$game': {
      id: '/_authenticated/app/games/$game'
      path: '/games/$game'
      fullPath: '/app/games/$game'
      preLoaderRoute: typeof AuthenticatedAppGamesGameRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$peerId': {
      id: '/_authenticated/app/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/app/chat/$peerId'
      preLoaderRoute: typeof AuthenticatedAppChatPeerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/call/$peerId': {
      id: '/_authenticated/app/call/$peerId'
      path: '/call/$peerId'
      fullPath: '/app/call/$peerId'
      preLoaderRoute: typeof AuthenticatedAppCallPeerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movies/$id/watch': {
      id: '/_authenticated/app/movies/$id/watch'
      path: '/watch'
      fullPath: '/app/movies/$id/watch'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdWatchRouteImport
      parentRoute: typeof AuthenticatedAppMoviesIdRoute
    }
    '/_authenticated/app/movies/$id/party': {
      id: '/_authenticated/app/movies/$id/party'
      path: '/party'
      fullPath: '/app/movies/$id/party'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdPartyRouteImport
      parentRoute: typeof AuthenticatedAppMoviesIdRoute
    }
    '/_authenticated/app/chat/group/$groupId': {
      id: '/_authenticated/app/chat/group/$groupId'
      path: '/chat/group/$groupId'
      fullPath: '/app/chat/group/$groupId'
      preLoaderRoute: typeof AuthenticatedAppChatGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/call/group/$groupId': {
      id: '/_authenticated/app/call/group/$groupId'
      path: '/call/group/$groupId'
      fullPath: '/app/call/group/$groupId'
      preLoaderRoute: typeof AuthenticatedAppCallGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/group/$groupId/': {
      id: '/_authenticated/app/chat/group/$groupId/'
      path: '/'
      fullPath: '/app/chat/group/$groupId/'
      preLoaderRoute: typeof AuthenticatedAppChatGroupGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatGroupGroupIdRoute
    }
    '/_authenticated/app/chat/group/$groupId/settings': {
      id: '/_authenticated/app/chat/group/$groupId/settings'
      path: '/settings'
      fullPath: '/app/chat/group/$groupId/settings'
      preLoaderRoute: typeof AuthenticatedAppChatGroupGroupIdSettingsRouteImport
      parentRoute: typeof AuthenticatedAppChatGroupGroupIdRoute
    }
    '/_authenticated/app/chat/group/$groupId/info': {
      id: '/_authenticated/app/chat/group/$groupId/info'
      path: '/info'
      fullPath: '/app/chat/group/$groupId/info'
      preLoaderRoute: typeof AuthenticatedAppChatGroupGroupIdInfoRouteImport
      parentRoute: typeof AuthenticatedAppChatGroupGroupIdRoute
    }
    '/_authenticated/app/movies/$id/episode/$season/$episode': {
      id: '/_authenticated/app/movies/$id/episode/$season/$episode'
      path: '/episode/$season/$episode'
      fullPath: '/app/movies/$id/episode/$season/$episode'
      preLoaderRoute: typeof AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRouteImport
      parentRoute: typeof AuthenticatedAppMoviesIdRoute
    }
  }
}

interface AuthenticatedAppMoviesIdRouteChildren {
  AuthenticatedAppMoviesIdPartyRoute: typeof AuthenticatedAppMoviesIdPartyRoute
  AuthenticatedAppMoviesIdWatchRoute: typeof AuthenticatedAppMoviesIdWatchRoute
  AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute: typeof AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute
}

const AuthenticatedAppMoviesIdRouteChildren: AuthenticatedAppMoviesIdRouteChildren =
  {
    AuthenticatedAppMoviesIdPartyRoute: AuthenticatedAppMoviesIdPartyRoute,
    AuthenticatedAppMoviesIdWatchRoute: AuthenticatedAppMoviesIdWatchRoute,
    AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute:
      AuthenticatedAppMoviesIdEpisodeSeasonEpisodeRoute,
  }

const AuthenticatedAppMoviesIdRouteWithChildren =
  AuthenticatedAppMoviesIdRoute._addFileChildren(
    AuthenticatedAppMoviesIdRouteChildren,
  )

interface AuthenticatedAppMoviesRouteChildren {
  AuthenticatedAppMoviesIdRoute: typeof AuthenticatedAppMoviesIdRouteWithChildren
  AuthenticatedAppMoviesListRoute: typeof AuthenticatedAppMoviesListRoute
  AuthenticatedAppMoviesIndexRoute: typeof AuthenticatedAppMoviesIndexRoute
}

const AuthenticatedAppMoviesRouteChildren: AuthenticatedAppMoviesRouteChildren =
  {
    AuthenticatedAppMoviesIdRoute: AuthenticatedAppMoviesIdRouteWithChildren,
    AuthenticatedAppMoviesListRoute: AuthenticatedAppMoviesListRoute,
    AuthenticatedAppMoviesIndexRoute: AuthenticatedAppMoviesIndexRoute,
  }

const AuthenticatedAppMoviesRouteWithChildren =
  AuthenticatedAppMoviesRoute._addFileChildren(
    AuthenticatedAppMoviesRouteChildren,
  )

interface AuthenticatedAppChatGroupGroupIdRouteChildren {
  AuthenticatedAppChatGroupGroupIdInfoRoute: typeof AuthenticatedAppChatGroupGroupIdInfoRoute
  AuthenticatedAppChatGroupGroupIdSettingsRoute: typeof AuthenticatedAppChatGroupGroupIdSettingsRoute
  AuthenticatedAppChatGroupGroupIdIndexRoute: typeof AuthenticatedAppChatGroupGroupIdIndexRoute
}

const AuthenticatedAppChatGroupGroupIdRouteChildren: AuthenticatedAppChatGroupGroupIdRouteChildren =
  {
    AuthenticatedAppChatGroupGroupIdInfoRoute:
      AuthenticatedAppChatGroupGroupIdInfoRoute,
    AuthenticatedAppChatGroupGroupIdSettingsRoute:
      AuthenticatedAppChatGroupGroupIdSettingsRoute,
    AuthenticatedAppChatGroupGroupIdIndexRoute:
      AuthenticatedAppChatGroupGroupIdIndexRoute,
  }

const AuthenticatedAppChatGroupGroupIdRouteWithChildren =
  AuthenticatedAppChatGroupGroupIdRoute._addFileChildren(
    AuthenticatedAppChatGroupGroupIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnniversaryRoute: typeof AuthenticatedAppAnniversaryRoute
  AuthenticatedAppBucketRoute: typeof AuthenticatedAppBucketRoute
  AuthenticatedAppCallsRoute: typeof AuthenticatedAppCallsRoute
  AuthenticatedAppChessRoute: typeof AuthenticatedAppChessRoute
  AuthenticatedAppConciergeRoute: typeof AuthenticatedAppConciergeRoute
  AuthenticatedAppConstellationRoute: typeof AuthenticatedAppConstellationRoute
  AuthenticatedAppCouponsRoute: typeof AuthenticatedAppCouponsRoute
  AuthenticatedAppDailyChallengeRoute: typeof AuthenticatedAppDailyChallengeRoute
  AuthenticatedAppFriendsRoute: typeof AuthenticatedAppFriendsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppHideseekRoute: typeof AuthenticatedAppHideseekRoute
  AuthenticatedAppInviteRoute: typeof AuthenticatedAppInviteRoute
  AuthenticatedAppJournalRoute: typeof AuthenticatedAppJournalRoute
  AuthenticatedAppKnowmeRoute: typeof AuthenticatedAppKnowmeRoute
  AuthenticatedAppLoveQuizRoute: typeof AuthenticatedAppLoveQuizRoute
  AuthenticatedAppLudoRoute: typeof AuthenticatedAppLudoRoute
  AuthenticatedAppMeRoute: typeof AuthenticatedAppMeRoute
  AuthenticatedAppMemoriesRoute: typeof AuthenticatedAppMemoriesRoute
  AuthenticatedAppMemoryChallengeRoute: typeof AuthenticatedAppMemoryChallengeRoute
  AuthenticatedAppMoodRoute: typeof AuthenticatedAppMoodRoute
  AuthenticatedAppMoviesRoute: typeof AuthenticatedAppMoviesRouteWithChildren
  AuthenticatedAppPaintRoute: typeof AuthenticatedAppPaintRoute
  AuthenticatedAppPartnerRoute: typeof AuthenticatedAppPartnerRoute
  AuthenticatedAppPlayRoute: typeof AuthenticatedAppPlayRoute
  AuthenticatedAppPoolRoute: typeof AuthenticatedAppPoolRoute
  AuthenticatedAppPuzzleRoute: typeof AuthenticatedAppPuzzleRoute
  AuthenticatedAppRitualsRoute: typeof AuthenticatedAppRitualsRoute
  AuthenticatedAppScribbleRoute: typeof AuthenticatedAppScribbleRoute
  AuthenticatedAppShopRoute: typeof AuthenticatedAppShopRoute
  AuthenticatedAppTamannaRoute: typeof AuthenticatedAppTamannaRoute
  AuthenticatedAppTimelineRoute: typeof AuthenticatedAppTimelineRoute
  AuthenticatedAppTriviaRoute: typeof AuthenticatedAppTriviaRoute
  AuthenticatedAppUnoRoute: typeof AuthenticatedAppUnoRoute
  AuthenticatedAppWatchRoute: typeof AuthenticatedAppWatchRoute
  AuthenticatedAppWatchlistRoute: typeof AuthenticatedAppWatchlistRoute
  AuthenticatedAppWishlistRoute: typeof AuthenticatedAppWishlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCallPeerIdRoute: typeof AuthenticatedAppCallPeerIdRoute
  AuthenticatedAppChatPeerIdRoute: typeof AuthenticatedAppChatPeerIdRoute
  AuthenticatedAppGamesGameRoute: typeof AuthenticatedAppGamesGameRoute
  AuthenticatedAppGroupMatchMatchIdRoute: typeof AuthenticatedAppGroupMatchMatchIdRoute
  AuthenticatedAppLettersIdRoute: typeof AuthenticatedAppLettersIdRoute
  AuthenticatedAppUserUserIdRoute: typeof AuthenticatedAppUserUserIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
  AuthenticatedAppLettersIndexRoute: typeof AuthenticatedAppLettersIndexRoute
  AuthenticatedAppCallGroupGroupIdRoute: typeof AuthenticatedAppCallGroupGroupIdRoute
  AuthenticatedAppChatGroupGroupIdRoute: typeof AuthenticatedAppChatGroupGroupIdRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnniversaryRoute: AuthenticatedAppAnniversaryRoute,
  AuthenticatedAppBucketRoute: AuthenticatedAppBucketRoute,
  AuthenticatedAppCallsRoute: AuthenticatedAppCallsRoute,
  AuthenticatedAppChessRoute: AuthenticatedAppChessRoute,
  AuthenticatedAppConciergeRoute: AuthenticatedAppConciergeRoute,
  AuthenticatedAppConstellationRoute: AuthenticatedAppConstellationRoute,
  AuthenticatedAppCouponsRoute: AuthenticatedAppCouponsRoute,
  AuthenticatedAppDailyChallengeRoute: AuthenticatedAppDailyChallengeRoute,
  AuthenticatedAppFriendsRoute: AuthenticatedAppFriendsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppHideseekRoute: AuthenticatedAppHideseekRoute,
  AuthenticatedAppInviteRoute: AuthenticatedAppInviteRoute,
  AuthenticatedAppJournalRoute: AuthenticatedAppJournalRoute,
  AuthenticatedAppKnowmeRoute: AuthenticatedAppKnowmeRoute,
  AuthenticatedAppLoveQuizRoute: AuthenticatedAppLoveQuizRoute,
  AuthenticatedAppLudoRoute: AuthenticatedAppLudoRoute,
  AuthenticatedAppMeRoute: AuthenticatedAppMeRoute,
  AuthenticatedAppMemoriesRoute: AuthenticatedAppMemoriesRoute,
  AuthenticatedAppMemoryChallengeRoute: AuthenticatedAppMemoryChallengeRoute,
  AuthenticatedAppMoodRoute: AuthenticatedAppMoodRoute,
  AuthenticatedAppMoviesRoute: AuthenticatedAppMoviesRouteWithChildren,
  AuthenticatedAppPaintRoute: AuthenticatedAppPaintRoute,
  AuthenticatedAppPartnerRoute: AuthenticatedAppPartnerRoute,
  AuthenticatedAppPlayRoute: AuthenticatedAppPlayRoute,
  AuthenticatedAppPoolRoute: AuthenticatedAppPoolRoute,
  AuthenticatedAppPuzzleRoute: AuthenticatedAppPuzzleRoute,
  AuthenticatedAppRitualsRoute: AuthenticatedAppRitualsRoute,
  AuthenticatedAppScribbleRoute: AuthenticatedAppScribbleRoute,
  AuthenticatedAppShopRoute: AuthenticatedAppShopRoute,
  AuthenticatedAppTamannaRoute: AuthenticatedAppTamannaRoute,
  AuthenticatedAppTimelineRoute: AuthenticatedAppTimelineRoute,
  AuthenticatedAppTriviaRoute: AuthenticatedAppTriviaRoute,
  AuthenticatedAppUnoRoute: AuthenticatedAppUnoRoute,
  AuthenticatedAppWatchRoute: AuthenticatedAppWatchRoute,
  AuthenticatedAppWatchlistRoute: AuthenticatedAppWatchlistRoute,
  AuthenticatedAppWishlistRoute: AuthenticatedAppWishlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCallPeerIdRoute: AuthenticatedAppCallPeerIdRoute,
  AuthenticatedAppChatPeerIdRoute: AuthenticatedAppChatPeerIdRoute,
  AuthenticatedAppGamesGameRoute: AuthenticatedAppGamesGameRoute,
  AuthenticatedAppGroupMatchMatchIdRoute:
    AuthenticatedAppGroupMatchMatchIdRoute,
  AuthenticatedAppLettersIdRoute: AuthenticatedAppLettersIdRoute,
  AuthenticatedAppUserUserIdRoute: AuthenticatedAppUserUserIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
  AuthenticatedAppLettersIndexRoute: AuthenticatedAppLettersIndexRoute,
  AuthenticatedAppCallGroupGroupIdRoute: AuthenticatedAppCallGroupGroupIdRoute,
  AuthenticatedAppChatGroupGroupIdRoute:
    AuthenticatedAppChatGroupGroupIdRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShowcaseRoute: ShowcaseRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiLivekitTokenRoute: ApiLivekitTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
